### PR TITLE
Corrected agent's process on updating in a container

### LINKED ISSUE #3587: Updates cause self-hosted agents to be removed
## Agent Version and Platform
Version of your agent? 2.185.1/2.193.1 (probably others, but these are the ones we have tested)

OS of the machine running the agent? Linux

## Azure DevOps Type and Version
https://dev.azure.com/jbaconsulting

## What's not working?
We are running our self-hosted agents on Linux containers in Docker, following the instructions given here: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#linux

The only modification we have made is to the `start.sh` script to configure the agent as an Environment agent (rather than a Deployment Group agent).

Whenever one of these agents updates (either as a self-update when running a task, or when manually triggered from the Deployment Group UI in Azure DevOps), the update process causes the agent to be removed. This is because the `start.sh` script removes the agent once the `run.sh` script exits (see the `cleanup()` function), which occurs when the agent exits as part of the update.

## Agent and Worker's Diagnostic Logs
<details>
  <summary>Agent command line output</summary>

```
1. Configuring Azure Pipelines agent...

  ___                      ______ _            _ _
 / _ \                     | ___ (_)          | (_)
/ /_\ \_____   _ _ __ ___  | |_/ /_ _ __   ___| |_ _ __   ___  ___
|  _  |_  / | | | '__/ _ \ |  __/| | '_ \ / _ \ | | '_ \ / _ \/ __|
| | | |/ /| |_| | | |  __/ | |   | | |_) |  __/ | | | | |  __/\__ \
\_| |_/___|\__,_|_|  \___| \_|   |_| .__/ \___|_|_|_| |_|\___||___/
                                   | |
        agent v2.185.1             |_|          (commit 45c52d0)


>> End User License Agreements:

Building sources from a TFVC repository requires accepting the Team Explorer Everywhere End User License Agreement. This step is not required for building sources from Git repositories.

A copy of the Team Explorer Everywhere license agreement can be found at:
  /azp/externals/tee/license.html


>> Connect:

Connecting to server ...

>> Register Agent:

Scanning for tool capabilities.
Connecting to the server.
Successfully added the agent
Testing agent connection.
2021-10-29 14:38:19Z: Settings Saved.
2. Running Azure Pipelines agent...
Scanning for tool capabilities.
Connecting to the server.
2021-10-29 14:38:21Z: Listening for Jobs
Agent update in progress, do not shutdown agent.
Downloading 2.194.0 agent
Waiting for current job finish running.
Generate and execute update script.
Agent will exit shortly for update, should back online within 10 seconds.
Cleanup. Removing Azure Pipelines agent...
Removing agent from the server
Connecting to server ...
Error reported in diagnostic logs. Please examine the log for more details.
    - /azp/_diag/Agent_20211029-150501-utc.log
Failed: Removing agent from the server
Agent "azure-pipelines-environment-agent-677c6c5d89-bc4mn" is running a job for pool "environment-2-f642640a-3d5c-4896-8fed-0b46ef1c29f6"
Retrying in 30 seconds...
renamed '/azp/_diag/SelfUpdate-20211029-150501.log' -> '/azp/_diag/SelfUpdate-20211029-150501.log.succeed'
Scanning for tool capabilities.
Connecting to the server.
2021-10-29 15:05:06Z: Listening for Jobs
2021-10-29 15:05:07Z: Running job: Deploy
2021-10-29 15:05:21Z: Job Deploy completed with result: Succeeded
Removing agent from the server
Connecting to server ...
Succeeded: Removing agent from the server
Removing .credentials
Succeeded: Removing .credentials
Removing .agent
Succeeded: Removing .agent
```
</details>

<details>
  <summary>Agent diagnostic logs (concatenated)</summary>

```
[2021-10-29 14:38:16Z INFO AgentProcess] Agent package linux-x64.
[2021-10-29 14:38:16Z INFO AgentProcess] Running on Linux (X64).
[2021-10-29 14:38:16Z INFO AgentProcess] RuntimeInformation: Linux 5.4.149-73.259.amzn2.x86_64 #1 SMP Mon Sep 27 12:48:12 UTC 2021.
[2021-10-29 14:38:16Z INFO AgentProcess] Version: 2.185.1
[2021-10-29 14:38:16Z INFO AgentProcess] Commit: 45c52d01eec6c18e3a3e5d8e2a4859fbfc90eff7
[2021-10-29 14:38:16Z INFO AgentProcess] Culture: 
[2021-10-29 14:38:16Z INFO AgentProcess] UI Culture: 
[2021-10-29 14:38:16Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 14:38:16Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 14:38:16Z INFO AgentProcess] Validating directory permissions for: '/azp'
[2021-10-29 14:38:16Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 14:38:16Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 14:38:17Z INFO CommandSettings] Configure {
  "AcceptTeeEula": true,
  "AddDeploymentGroupTags": false,
  "AddEnvironmentVirtualMachineResourceTags": false,
  "AddMachineGroupTags": false,
  "AlwaysExtractTask": false,
  "Agent": "azure-pipelines-environment-agent-677c6c5d89-bc4mn",
  "CollectionName": null,
  "DeploymentGroup": false,
  "DeploymentGroupName": null,
  "DeploymentGroupTags": null,
  "DeploymentPool": false,
  "DeploymentPoolName": null,
  "EnvironmentVMResource": true,
  "EnvironmentName": "NaFRA2 - Review Website",
  "EnvironmentVMResourceTags": null,
  "GitUseSChannel": false,
  "DisableLogUploads": false,
  "MachineGroup": false,
  "MachineGroupName": null,
  "MachineGroupTags": null,
  "MonitorSocketAddress": null,
  "NotificationPipeName": null,
  "NotificationSocketAddress": null,
  "NoRestart": false,
  "OverwriteAutoLogon": false,
  "Pool": null,
  "ProjectName": "NaFRA2",
  "ProxyPassword": null,
  "ProxyUserName": null,
  "ProxyUrl": null,
  "Replace": true,
  "RunAsAutoLogon": false,
  "RunAsService": false,
  "RunOnce": false,
  "SslCACert": null,
  "SslClientCert": null,
  "SslClientCertArchive": null,
  "SslClientCertKey": null,
  "SslClientCertPassword": null,
  "SslSkipCertValidation": false,
  "Url": "https://dev.azure.com/jbaconsulting/",
  "WindowsLogonAccount": null,
  "WindowsLogonPassword": null,
  "Work": "_work",
  "Auth": "PAT",
  "LaunchBrowser": false,
  "Password": null,
  "Token": "***",
  "Unattended": true,
  "UserName": null,
  "Help": false,
  "Version": false
}
[2021-10-29 14:38:17Z INFO AgentProcess] Arguments parsed
[2021-10-29 14:38:17Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 14:38:17Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 14:38:17Z INFO HostContext] Well known config file 'Proxy': '/azp/.proxy'
[2021-10-29 14:38:17Z INFO VstsAgentWebProxy] No proxy setting found.
[2021-10-29 14:38:17Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 14:38:17Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 14:38:17Z INFO HostContext] Well known config file 'Certificates': '/azp/.certificates'
[2021-10-29 14:38:17Z INFO AgentCertificateManager] No certificate setting found.
[2021-10-29 14:38:17Z INFO Agent] ExecuteCommand
[2021-10-29 14:38:17Z INFO ConfigurationStore] currentAssemblyLocation: /azp/bin/Agent.Listener.dll
[2021-10-29 14:38:17Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 14:38:17Z INFO ConfigurationStore] binPath: /azp/bin
[2021-10-29 14:38:17Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 14:38:17Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 14:38:17Z INFO ConfigurationStore] RootFolder: /azp
[2021-10-29 14:38:17Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 14:38:17Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 14:38:17Z INFO HostContext] Well known config file 'Agent': '/azp/.agent'
[2021-10-29 14:38:17Z INFO ConfigurationStore] ConfigFilePath: /azp/.agent
[2021-10-29 14:38:17Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 14:38:17Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 14:38:17Z INFO HostContext] Well known config file 'Credentials': '/azp/.credentials'
[2021-10-29 14:38:17Z INFO ConfigurationStore] CredFilePath: /azp/.credentials
[2021-10-29 14:38:17Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 14:38:17Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 14:38:17Z INFO HostContext] Well known config file 'Service': '/azp/.service'
[2021-10-29 14:38:17Z INFO ConfigurationStore] ServiceConfigFilePath: /azp/.service
[2021-10-29 14:38:17Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 14:38:17Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 14:38:17Z INFO HostContext] Well known config file 'Autologon': '/azp/.autologon'
[2021-10-29 14:38:17Z INFO ConfigurationStore] AutoLogonSettingsFilePath: /azp/.autologon
[2021-10-29 14:38:17Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 14:38:17Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 14:38:17Z INFO HostContext] Well known config file 'Options': '/azp/.options'
[2021-10-29 14:38:17Z INFO ConfigurationStore] RuntimeOptionsFilePath: /azp/.options
[2021-10-29 14:38:17Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 14:38:17Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 14:38:17Z INFO HostContext] Well known config file 'SetupInfo': '/azp/.setup_info'
[2021-10-29 14:38:17Z INFO ConfigurationStore] SetupInfoFilePath: /azp/.setup_info
[2021-10-29 14:38:17Z INFO Terminal] WRITE LINE: 
  ___                      ______ _            _ _
 / _ \                     | ___ (_)          | (_)
/ /_\ \_____   _ _ __ ___  | |_/ /_ _ __   ___| |_ _ __   ___  ___
|  _  |_  / | | | '__/ _ \ |  __/| | '_ \ / _ \ | | '_ \ / _ \/ __|
| | | |/ /| |_| | | |  __/ | |   | | |_) |  __/ | | | | |  __/\__ \
\_| |_/___|\__,_|_|  \___| \_|   |_| .__/ \___|_|_|_| |_|\___||___/
                                   | |
        agent v2.185.1             |_|          (commit 45c52d0)

[2021-10-29 14:38:17Z INFO ConfigurationManager] ConfigureAsync
[2021-10-29 14:38:17Z INFO ConfigurationStore] IsConfigured()
[2021-10-29 14:38:17Z INFO ConfigurationStore] IsConfigured: False
[2021-10-29 14:38:17Z INFO ConfigurationManager] Is configured: False
[2021-10-29 14:38:17Z INFO CommandSettings] Flag 'sslskipcertvalidation': 'False'
[2021-10-29 14:38:17Z INFO Terminal] WRITE LINE: 
[2021-10-29 14:38:17Z INFO Terminal] WRITE LINE: >> End User License Agreements:
[2021-10-29 14:38:17Z INFO Terminal] WRITE LINE: 
[2021-10-29 14:38:17Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 14:38:17Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 14:38:17Z INFO HostContext] Well known directory 'Externals': '/azp/externals'
[2021-10-29 14:38:17Z INFO Terminal] WRITE LINE: Building sources from a TFVC repository requires accepting the Team Explorer Everywhere End User License Agreement. This step is not required for building sources from Git repositories.

A copy of the Team Explorer Everywhere license agreement can be found at:
  /azp/externals/tee/license.html
[2021-10-29 14:38:17Z INFO Terminal] WRITE LINE: 
[2021-10-29 14:38:17Z INFO CommandSettings] Flag 'acceptteeeula': 'True'
[2021-10-29 14:38:17Z INFO CommandSettings] Flag 'deploymentgroup': 'False'
[2021-10-29 14:38:17Z INFO CommandSettings] Flag 'deploymentpool': 'False'
[2021-10-29 14:38:17Z INFO CommandSettings] Flag 'environment': 'True'
[2021-10-29 14:38:17Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Listener.Configuration.IConfigurationProvider'
[2021-10-29 14:38:17Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.BuildReleasesAgentConfigProvider, Agent.Listener
[2021-10-29 14:38:17Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.DeploymentGroupAgentConfigProvider, Agent.Listener
[2021-10-29 14:38:17Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.SharedDeploymentAgentConfigProvider, Agent.Listener
[2021-10-29 14:38:17Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.EnvironmentVMResourceConfigProvider, Agent.Listener
[2021-10-29 14:38:17Z INFO Terminal] WRITE LINE: 
[2021-10-29 14:38:17Z INFO Terminal] WRITE LINE: >> Connect:
[2021-10-29 14:38:17Z INFO Terminal] WRITE LINE: 
[2021-10-29 14:38:17Z INFO CommandSettings] Arg 'url': 'https://dev.azure.com/jbaconsulting/'
[2021-10-29 14:38:17Z INFO EnvironmentVMResourceConfigProvider] url - https://dev.azure.com/jbaconsulting/
[2021-10-29 14:38:17Z INFO ConfigurationManager] GetCredentialProvider
[2021-10-29 14:38:17Z INFO CommandSettings] Arg 'auth': 'PAT'
[2021-10-29 14:38:17Z INFO ConfigurationManager] Creating credential for auth: PAT
[2021-10-29 14:38:17Z INFO CredentialManager] GetCredentialProvider
[2021-10-29 14:38:17Z INFO CredentialManager] Creating type PAT
[2021-10-29 14:38:17Z INFO CredentialManager] Creating credential type: PAT
[2021-10-29 14:38:17Z INFO PersonalAccessToken] EnsureCredential
[2021-10-29 14:38:17Z INFO CommandSettings] Arg 'token': '***'
[2021-10-29 14:38:17Z INFO PersonalAccessToken] GetVssCredentials
[2021-10-29 14:38:17Z INFO PersonalAccessToken] token retrieved: 52 chars
[2021-10-29 14:38:17Z INFO PersonalAccessToken] cred created
[2021-10-29 14:38:17Z INFO ConfigurationManager] cred retrieved
[2021-10-29 14:38:17Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2021-10-29 14:38:17Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2021-10-29 14:38:17Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2021-10-29 14:38:17Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2021-10-29 14:38:17Z INFO ConfigurationManager] Server deployment type: Hosted
[2021-10-29 14:38:17Z INFO Terminal] WRITE LINE: Connecting to server ...
[2021-10-29 14:38:17Z INFO EnvironmentVMResourceConfigProvider] Test connection with environment
[2021-10-29 14:38:17Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2021-10-29 14:38:17Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2021-10-29 14:38:17Z INFO EnvironmentVMResourceConfigProvider] Connection complete for environment
[2021-10-29 14:38:17Z INFO ConfigurationManager] Test Connection complete.
[2021-10-29 14:38:17Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 14:38:17Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 14:38:17Z INFO HostContext] Well known config file 'RSACredentials': '/azp/.credentials_rsaparams'
[2021-10-29 14:38:17Z INFO RSAFileKeyManager] Creating new RSA key using 2048-bit key length
[2021-10-29 14:38:17Z INFO RSAFileKeyManager] Successfully saved RSA key parameters to file /azp/.credentials_rsaparams
[2021-10-29 14:38:17Z INFO RSAFileKeyManager] Which: 'chmod'
[2021-10-29 14:38:17Z INFO RSAFileKeyManager] Location: '{matches.First()}'
[2021-10-29 14:38:17Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 14:38:17Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 14:38:17Z INFO ProcessInvokerWrapper] Starting process:
[2021-10-29 14:38:17Z INFO ProcessInvokerWrapper]   File name: '/bin/chmod'
[2021-10-29 14:38:17Z INFO ProcessInvokerWrapper]   Arguments: '600 /azp/.credentials_rsaparams'
[2021-10-29 14:38:17Z INFO ProcessInvokerWrapper]   Working directory: '/azp'
[2021-10-29 14:38:17Z INFO ProcessInvokerWrapper]   Require exit code zero: 'False'
[2021-10-29 14:38:17Z INFO ProcessInvokerWrapper]   Encoding web name:  ; code page: ''
[2021-10-29 14:38:17Z INFO ProcessInvokerWrapper]   Force kill process on cancellation: 'False'
[2021-10-29 14:38:17Z INFO ProcessInvokerWrapper]   Redirected STDIN: 'False'
[2021-10-29 14:38:17Z INFO ProcessInvokerWrapper]   Persist current code page: 'False'
[2021-10-29 14:38:17Z INFO ProcessInvokerWrapper]   Keep redirected STDIN open: 'False'
[2021-10-29 14:38:17Z INFO ProcessInvokerWrapper]   High priority process: 'False'
[2021-10-29 14:38:17Z INFO ProcessInvokerWrapper] Failed to update oom_score_adj for PID: 66.
[2021-10-29 14:38:17Z INFO ProcessInvokerWrapper] Exited process 66 with exit code 0
[2021-10-29 14:38:18Z INFO ProcessInvokerWrapper] System.IO.DirectoryNotFoundException: Could not find a part of the path '/proc/66/oom_score_adj'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path)
   at System.IO.File.WriteAllText(String path, String contents)
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.WriteProcessOomScoreAdj(Int32 processId, Int32 oomScoreAdj)
[2021-10-29 14:38:18Z INFO ProcessInvokerWrapper] Process started with process id 66, waiting for process exit.
[2021-10-29 14:38:18Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2021-10-29 14:38:18Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2021-10-29 14:38:18Z INFO ProcessInvokerWrapper] Finished process 66 with exit code 0, and elapsed time 00:00:00.0123139.
[2021-10-29 14:38:18Z INFO RSAFileKeyManager] Successfully set permissions for RSA key parameters file /azp/.credentials_rsaparams
[2021-10-29 14:38:18Z INFO Terminal] WRITE LINE: 
[2021-10-29 14:38:18Z INFO Terminal] WRITE LINE: >> Register Agent:
[2021-10-29 14:38:18Z INFO Terminal] WRITE LINE: 
[2021-10-29 14:38:18Z INFO CommandSettings] Arg 'projectname': 'NaFRA2'
[2021-10-29 14:38:18Z INFO EnvironmentVMResourceConfigProvider] vm resource will be configured against the environment 'NaFRA2 - Review Website'
[2021-10-29 14:38:18Z INFO EnvironmentVMResourceConfigProvider] Found environment NaFRA2 - Review Website with id 2
[2021-10-29 14:38:18Z INFO EnvironmentVMResourceConfigProvider] vm resource configuration: environment id: '2', project name: '', project id: '9f91a63f-06b8-4e02-987b-e6b84d64dd8e'
[2021-10-29 14:38:18Z INFO CommandSettings] Arg 'agent': 'azure-pipelines-environment-agent-677c6c5d89-bc4mn'
[2021-10-29 14:38:18Z INFO Terminal] WRITE LINE: Scanning for tool capabilities.
[2021-10-29 14:38:18Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Capabilities.ICapabilitiesProvider'
[2021-10-29 14:38:18Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Capabilities.AgentCapabilitiesProvider, Microsoft.VisualStudio.Services.Agent
[2021-10-29 14:38:18Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Capabilities.EnvironmentCapabilitiesProvider, Microsoft.VisualStudio.Services.Agent
[2021-10-29 14:38:18Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Capabilities.NixCapabilitiesProvider, Microsoft.VisualStudio.Services.Agent
[2021-10-29 14:38:18Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Capabilities.UserCapabilitiesProvider, Microsoft.VisualStudio.Services.Agent
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Ignore: 'AZP_TOKEN'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Ignore: 'AZP_TOKEN_FILE'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Adding '_': './bin/Agent.Listener'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Adding 'AGENT_ALLOW_RUNASROOT': '1'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Adding 'AZP_ENVIRONMENT': 'NaFRA2 - Review Website'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Adding 'AZP_PROJECT': 'NaFRA2'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Adding 'AZP_URL': 'https://dev.azure.com/jbaconsulting/'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Adding 'DEBIAN_FRONTEND': 'noninteractive'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Adding 'HOME': '/root'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Adding 'HOSTNAME': 'azure-pipelines-environment-agent-677c6c5d89-bc4mn'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Adding 'KUBERNETES_PORT': 'tcp://172.20.0.1:443'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Adding 'KUBERNETES_PORT_443_TCP': 'tcp://172.20.0.1:443'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Adding 'KUBERNETES_PORT_443_TCP_ADDR': '172.20.0.1'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Adding 'KUBERNETES_PORT_443_TCP_PORT': '443'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Adding 'KUBERNETES_PORT_443_TCP_PROTO': 'tcp'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Adding 'KUBERNETES_SERVICE_HOST': '172.20.0.1'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Adding 'KUBERNETES_SERVICE_PORT': '443'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Adding 'KUBERNETES_SERVICE_PORT_HTTPS': '443'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPPROXY_PORT': 'tcp://172.20.204.73:80'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPPROXY_PORT_80_TCP': 'tcp://172.20.204.73:80'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPPROXY_PORT_80_TCP_ADDR': '172.20.204.73'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPPROXY_PORT_80_TCP_PORT': '80'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPPROXY_PORT_80_TCP_PROTO': 'tcp'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPPROXY_SERVICE_HOST': '172.20.204.73'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPPROXY_SERVICE_PORT': '80'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPSERVER_PORT': 'tcp://172.20.143.39:80'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPSERVER_PORT_80_TCP': 'tcp://172.20.143.39:80'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPSERVER_PORT_80_TCP_ADDR': '172.20.143.39'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPSERVER_PORT_80_TCP_PORT': '80'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPSERVER_PORT_80_TCP_PROTO': 'tcp'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPSERVER_SERVICE_HOST': '172.20.143.39'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPSERVER_SERVICE_PORT': '80'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Adding 'OLDPWD': '/azp'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Adding 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Adding 'PWD': '/azp'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Adding 'REVIEW_WEBSITE_PORT': 'tcp://172.20.218.41:80'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Adding 'REVIEW_WEBSITE_PORT_80_TCP': 'tcp://172.20.218.41:80'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Adding 'REVIEW_WEBSITE_PORT_80_TCP_ADDR': '172.20.218.41'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Adding 'REVIEW_WEBSITE_PORT_80_TCP_PORT': '80'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Adding 'REVIEW_WEBSITE_PORT_80_TCP_PROTO': 'tcp'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Adding 'REVIEW_WEBSITE_SERVICE_HOST': '172.20.218.41'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Adding 'REVIEW_WEBSITE_SERVICE_PORT': '80'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Skipping: 'SHLVL'
[2021-10-29 14:38:18Z INFO EnvironmentCapabilitiesProvider] Adding 'VSO_AGENT_IGNORE': 'AZP_TOKEN,AZP_TOKEN_FILE'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Which: 'android'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Checking file: 'tools/android'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Checking file: '/root/Library/Developer/Xamarin/android-sdk-macosx/tools/android'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Which: 'ant'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Which: 'waagent'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Which: 'bundle'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Which: 'clang'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Which: 'cmake'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Which: 'curl'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Location: '{matches.First()}'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Adding 'curl': '/usr/bin/curl'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Which: 'docker'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Which: 'dotnet'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Which: 'git'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Location: '{matches.First()}'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Adding 'git': '/usr/bin/git'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Which: 'gulp'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Which: 'java'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Which: 'javac'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Which: 'make'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Which: 'mvn'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Which: 'xbuild'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Checking file: '/Library/Frameworks/Mono.framework/Commands/xbuild'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Which: 'msbuild'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Checking file: '/Library/Frameworks/Mono.framework/Commands/msbuild'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Which: 'node'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Which: 'nodejs'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Which: 'npm'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Which: 'python'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Which: 'python3'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Location: '{matches.First()}'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Adding 'python3': '/usr/bin/python3'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Which: 'sh'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Location: '{matches.First()}'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Adding 'sh': '/bin/sh'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Which: 'svn'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Which: 'ruby'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Which: 'rake'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Which: 'svn'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Which: 'mdtool'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Checking file: '/Applications/Xamarin Studio.app/Contents/MacOS/mdtool'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Checking file: '/Applications/Visual Studio.app/Contents/MacOS/vstool'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Which: 'generator'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Checking file: '/Library/Frameworks/Xamarin.Android.framework/Commands/generator'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Checking file: '/Library/Frameworks/Xamarin.Android.framework/Versions/Current/Version'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Which: 'xcode-select'
[2021-10-29 14:38:18Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:18Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 14:38:18Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 14:38:18Z INFO AgentCapabilitiesProvider] Adding 'Agent.Name': 'azure-pipelines-environment-agent-677c6c5d89-bc4mn'
[2021-10-29 14:38:18Z INFO AgentCapabilitiesProvider] Adding 'Agent.OS': 'Linux'
[2021-10-29 14:38:18Z INFO AgentCapabilitiesProvider] Adding 'Agent.OSArchitecture': 'X64'
[2021-10-29 14:38:18Z INFO AgentCapabilitiesProvider] Adding 'InteractiveSession': 'True'
[2021-10-29 14:38:18Z INFO AgentCapabilitiesProvider] Adding 'Agent.Version': '2.185.1'
[2021-10-29 14:38:18Z INFO AgentCapabilitiesProvider] Adding 'Agent.ComputerName': 'azure-pipelines-environment-agent-677c6c5d89-bc4mn'
[2021-10-29 14:38:18Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 14:38:18Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 14:38:18Z INFO AgentCapabilitiesProvider] Adding 'Agent.HomeDirectory': '/azp'
[2021-10-29 14:38:18Z INFO Terminal] WRITE LINE: Connecting to the server.
[2021-10-29 14:38:18Z INFO CommandSettings] Flag 'addvirtualmachineresourcetags': 'False'
[2021-10-29 14:38:18Z INFO CommandSettings] Flag 'addvirtualmachineresourcetags': 'False'
[2021-10-29 14:38:18Z INFO CommandSettings] Flag 'unattended': 'True'
[2021-10-29 14:38:18Z INFO PromptManager] ReadValue
[2021-10-29 14:38:18Z INFO EnvironmentVMResourceConfigProvider] Environment virtual machine resource with name: 'azure-pipelines-environment-agent-677c6c5d89-bc4mn', id: '25' has been added successfully.
[2021-10-29 14:38:18Z INFO EnvironmentVMResourceConfigProvider] environment pool id: '28'
[2021-10-29 14:38:18Z INFO Terminal] WRITE LINE: Successfully added the agent
[2021-10-29 14:38:18Z INFO ConfigurationManager] Agent server url resolve by server: 'https://dev.azure.com/jbaconsulting/'.
[2021-10-29 14:38:18Z INFO ConfigurationStore] Saving OAuth credential @ /azp/.credentials
[2021-10-29 14:38:18Z INFO ConfigurationStore] Credentials Saved.
[2021-10-29 14:38:18Z INFO Terminal] WRITE LINE: Testing agent connection.
[2021-10-29 14:38:18Z INFO ConfigurationStore] HasCredentials()
[2021-10-29 14:38:18Z INFO ConfigurationStore] stored True
[2021-10-29 14:38:18Z INFO CredentialManager] GetCredentialProvider
[2021-10-29 14:38:18Z INFO CredentialManager] Creating type OAuth
[2021-10-29 14:38:18Z INFO CredentialManager] Creating credential type: OAuth
[2021-10-29 14:38:18Z INFO RSAFileKeyManager] Loading RSA key parameters from file /azp/.credentials_rsaparams
[2021-10-29 14:38:18Z INFO AgentServer] Establish connection with 100 seconds timeout.
[2021-10-29 14:38:19Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2021-10-29 14:38:19Z WARN VisualStudioServices] Authentication failed with status code 401.
Cache-Control: no-cache
Pragma: no-cache
P3P: CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
WWW-Authenticate: Bearer authorization_uri=https://login.microsoftonline.com/3131e85c-e560-4bb3-a82f-8b339ad41833, Basic realm="https://tfsprodweusu4.app.visualstudio.com/", TFS-Federated
X-TFS-ProcessId: 0e99c790-05f9-425f-940a-ec6c7539ad80
Strict-Transport-Security: max-age=31536000; includeSubDomains
ActivityId: 457eff43-4971-45ec-ae2b-aabbb254e26a
X-TFS-Session: 39410a63-f25b-4b9c-a3f6-5906f37bc65c
X-VSS-E2EID: 1ef892de-d99e-484e-b74c-d88463e098ef
X-VSS-SenderDeploymentId: 3dbbfbca-3f3a-b896-0b3a-ea9e2087c7ac
X-Frame-Options: SAMEORIGIN
X-TFS-FedAuthRealm: https://tfsprodweusu4.app.visualstudio.com/
X-TFS-FedAuthIssuer: https://dev.azure.com/jbaconsulting/
X-VSS-AuthorizationEndpoint: https://vssps.dev.azure.com/jbaconsulting/
X-VSS-ResourceTenant: 3131e85c-e560-4bb3-a82f-8b339ad41833
X-VSS-S2STargetService: 00000002-0000-8888-8000-000000000000/visualstudio.com
X-TFS-FedAuthRedirect: https://spsprodweu2.vssps.visualstudio.com/_signin?realm=dev.azure.com&reply_to=https%3A%2F%2Fdev.azure.com%2Fjbaconsulting%2F_apis%2FconnectionData%3FconnectOptions%3D0%26lastChangeId%3D330326078%26lastChangeId64%3D330326078&redirect=1&hid=e8357ffe-403f-41bc-aae2-5d67ba1a7daa&context=eyJodCI6MiwiaGlkIjoiN2U4ZGZmYWUtYTA2Yy00MzI1LWE4MWQtZGE1NmY5ZTg5YjY4IiwicXMiOnt9LCJyciI6IiIsInZoIjoiIiwiY3YiOiIiLCJjcyI6IiJ90#ctx=eyJTaWduSW5Db29raWVEb21haW5zIjpbImh0dHBzOi8vbG9naW4ubWljcm9zb2Z0b25saW5lLmNvbSIsImh0dHBzOi8vbG9naW4ubWljcm9zb2Z0b25saW5lLmNvbSJdfQ2
Request-Context: appId=cid-v1:3142c212-5102-492c-94e2-153eb747f4c0
Access-Control-Expose-Headers: Request-Context
X-Content-Type-Options: nosniff
X-Cache: CONFIG_NOCACHE
X-MSEdge-Ref: Ref A: 31AA356D1BC04E67B6E78328A7CBF781 Ref B: LTSEDGE0816 Ref C: 2021-10-29T14:38:19Z
Date: Fri, 29 Oct 2021 14:38:18 GMT

[2021-10-29 14:38:19Z INFO RSAFileKeyManager] Loading RSA key parameters from file /azp/.credentials_rsaparams
[2021-10-29 14:38:19Z INFO RSAFileKeyManager] Loading RSA key parameters from file /azp/.credentials_rsaparams
[2021-10-29 14:38:19Z INFO VisualStudioServices] AAD Correlation ID for this token request: Unknown
[2021-10-29 14:38:19Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2021-10-29 14:38:19Z INFO AgentServer] Establish connection with 60 seconds timeout.
[2021-10-29 14:38:19Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2021-10-29 14:38:19Z INFO AgentServer] Establish connection with 60 seconds timeout.
[2021-10-29 14:38:19Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2021-10-29 14:38:19Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2021-10-29 14:38:19Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2021-10-29 14:38:19Z INFO CommandSettings] Arg 'work': '_work'
[2021-10-29 14:38:19Z INFO CommandSettings] Flag 'disableloguploads': 'False'
[2021-10-29 14:38:19Z INFO CommandSettings] Flag 'alwaysextracttask': 'False'
[2021-10-29 14:38:19Z INFO CommandSettings] Flag 'unattended': 'True'
[2021-10-29 14:38:19Z INFO PromptManager] ReadValue
[2021-10-29 14:38:19Z INFO ConfigurationStore] Saving agent settings.
[2021-10-29 14:38:19Z INFO ConfigurationStore] Settings Saved.
[2021-10-29 14:38:19Z INFO Terminal] WRITE LINE: 2021-10-29 14:38:19Z: Settings Saved.
[2021-10-29 14:38:19Z INFO SystemDControlManager] Service name 'vsts.agent.jbaconsulting..azure-pipelines-environment-agent-677c6c5d89-b.service' display name 'Azure Pipelines Agent (jbaconsulting..azure-pipelines-environment-agent-677c6c5d89-bc4mn)' will be used for service configuration.
[2021-10-29 14:38:19Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 14:38:19Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 14:38:19Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 14:38:19Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 14:38:19Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 14:38:19Z INFO UnixUtil] Which: 'chmod'
[2021-10-29 14:38:19Z INFO UnixUtil] Location: '{matches.First()}'
[2021-10-29 14:38:19Z INFO UnixUtil] Running /bin/chmod 755 "/azp/svc.sh"
[2021-10-29 14:38:19Z INFO ProcessInvokerWrapper] Starting process:
[2021-10-29 14:38:19Z INFO ProcessInvokerWrapper]   File name: '/bin/chmod'
[2021-10-29 14:38:19Z INFO ProcessInvokerWrapper]   Arguments: '755 "/azp/svc.sh"'
[2021-10-29 14:38:19Z INFO ProcessInvokerWrapper]   Working directory: '/azp'
[2021-10-29 14:38:19Z INFO ProcessInvokerWrapper]   Require exit code zero: 'True'
[2021-10-29 14:38:19Z INFO ProcessInvokerWrapper]   Encoding web name:  ; code page: ''
[2021-10-29 14:38:19Z INFO ProcessInvokerWrapper]   Force kill process on cancellation: 'False'
[2021-10-29 14:38:19Z INFO ProcessInvokerWrapper]   Redirected STDIN: 'False'
[2021-10-29 14:38:19Z INFO ProcessInvokerWrapper]   Persist current code page: 'False'
[2021-10-29 14:38:19Z INFO ProcessInvokerWrapper]   Keep redirected STDIN open: 'False'
[2021-10-29 14:38:19Z INFO ProcessInvokerWrapper]   High priority process: 'False'
[2021-10-29 14:38:19Z INFO ProcessInvokerWrapper] Failed to update oom_score_adj for PID: 70.
[2021-10-29 14:38:19Z INFO ProcessInvokerWrapper] Exited process 70 with exit code 0
[2021-10-29 14:38:19Z INFO ProcessInvokerWrapper] System.UnauthorizedAccessException: Access to the path '/proc/70/oom_score_adj' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.FlushWriteBuffer()
   at System.IO.FileStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.StreamWriter.CloseStreamFromDispose(Boolean disposing)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at System.IO.File.WriteAllText(String path, String contents)
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.WriteProcessOomScoreAdj(Int32 processId, Int32 oomScoreAdj)
[2021-10-29 14:38:19Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2021-10-29 14:38:19Z INFO ProcessInvokerWrapper] Process started with process id 70, waiting for process exit.
[2021-10-29 14:38:19Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2021-10-29 14:38:19Z INFO ProcessInvokerWrapper] Finished process 70 with exit code 0, and elapsed time 00:00:00.0013649.
[2021-10-29 14:38:19Z INFO AgentProcess] Agent package linux-x64.
[2021-10-29 14:38:19Z INFO AgentProcess] Running on Linux (X64).
[2021-10-29 14:38:19Z INFO AgentProcess] RuntimeInformation: Linux 5.4.149-73.259.amzn2.x86_64 #1 SMP Mon Sep 27 12:48:12 UTC 2021.
[2021-10-29 14:38:19Z INFO AgentProcess] Version: 2.185.1
[2021-10-29 14:38:19Z INFO AgentProcess] Commit: 45c52d01eec6c18e3a3e5d8e2a4859fbfc90eff7
[2021-10-29 14:38:19Z INFO AgentProcess] Culture: 
[2021-10-29 14:38:19Z INFO AgentProcess] UI Culture: 
[2021-10-29 14:38:19Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 14:38:19Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 14:38:19Z INFO AgentProcess] Validating directory permissions for: '/azp'
[2021-10-29 14:38:19Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 14:38:19Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 14:38:19Z INFO CommandSettings] Run {
  "Commit": false,
  "Diagnostics": false,
  "RunOnce": false,
  "StartupType": null,
  "Help": false,
  "Version": false
}
[2021-10-29 14:38:19Z INFO AgentProcess] Arguments parsed
[2021-10-29 14:38:19Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 14:38:19Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 14:38:19Z INFO HostContext] Well known config file 'Proxy': '/azp/.proxy'
[2021-10-29 14:38:19Z INFO VstsAgentWebProxy] No proxy setting found.
[2021-10-29 14:38:19Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 14:38:19Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 14:38:19Z INFO HostContext] Well known config file 'Certificates': '/azp/.certificates'
[2021-10-29 14:38:19Z INFO AgentCertificateManager] No certificate setting found.
[2021-10-29 14:38:19Z INFO Agent] ExecuteCommand
[2021-10-29 14:38:19Z INFO ConfigurationStore] currentAssemblyLocation: /azp/bin/Agent.Listener.dll
[2021-10-29 14:38:19Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 14:38:19Z INFO ConfigurationStore] binPath: /azp/bin
[2021-10-29 14:38:19Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 14:38:19Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 14:38:19Z INFO ConfigurationStore] RootFolder: /azp
[2021-10-29 14:38:19Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 14:38:19Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 14:38:19Z INFO HostContext] Well known config file 'Agent': '/azp/.agent'
[2021-10-29 14:38:19Z INFO ConfigurationStore] ConfigFilePath: /azp/.agent
[2021-10-29 14:38:19Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 14:38:19Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 14:38:19Z INFO HostContext] Well known config file 'Credentials': '/azp/.credentials'
[2021-10-29 14:38:19Z INFO ConfigurationStore] CredFilePath: /azp/.credentials
[2021-10-29 14:38:19Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 14:38:19Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 14:38:19Z INFO HostContext] Well known config file 'Service': '/azp/.service'
[2021-10-29 14:38:19Z INFO ConfigurationStore] ServiceConfigFilePath: /azp/.service
[2021-10-29 14:38:19Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 14:38:19Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 14:38:19Z INFO HostContext] Well known config file 'Autologon': '/azp/.autologon'
[2021-10-29 14:38:19Z INFO ConfigurationStore] AutoLogonSettingsFilePath: /azp/.autologon
[2021-10-29 14:38:19Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 14:38:19Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 14:38:19Z INFO HostContext] Well known config file 'Options': '/azp/.options'
[2021-10-29 14:38:19Z INFO ConfigurationStore] RuntimeOptionsFilePath: /azp/.options
[2021-10-29 14:38:19Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 14:38:19Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 14:38:19Z INFO HostContext] Well known config file 'SetupInfo': '/azp/.setup_info'
[2021-10-29 14:38:19Z INFO ConfigurationStore] SetupInfoFilePath: /azp/.setup_info
[2021-10-29 14:38:19Z INFO ConfigurationManager] LoadSettings
[2021-10-29 14:38:19Z INFO ConfigurationStore] IsConfigured()
[2021-10-29 14:38:19Z INFO ConfigurationStore] IsConfigured: True
[2021-10-29 14:38:19Z INFO ConfigurationManager] Is configured: True
[2021-10-29 14:38:19Z INFO ConfigurationStore] Read setting file: 320 chars
[2021-10-29 14:38:19Z INFO ConfigurationManager] Settings Loaded
[2021-10-29 14:38:19Z INFO ConfigurationStore] IsServiceConfigured()
[2021-10-29 14:38:19Z INFO ConfigurationStore] IsServiceConfigured: False
[2021-10-29 14:38:19Z INFO ConfigurationStore] IsConfigured()
[2021-10-29 14:38:19Z INFO ConfigurationStore] IsConfigured: True
[2021-10-29 14:38:19Z INFO ConfigurationManager] Is configured: True
[2021-10-29 14:38:19Z INFO Agent] Could not parse the argument value '' for StartupType. Defaulting to Manual
[2021-10-29 14:38:19Z INFO Agent] Set agent startup type - Manual
[2021-10-29 14:38:19Z INFO CommandSettings] Flag 'once': 'False'
[2021-10-29 14:38:19Z INFO CommandSettings] Flag 'once': 'False'
[2021-10-29 14:38:19Z INFO Agent] RunAsync
[2021-10-29 14:38:19Z INFO ConfigurationManager] LoadSettings
[2021-10-29 14:38:20Z INFO ConfigurationStore] IsConfigured()
[2021-10-29 14:38:20Z INFO ConfigurationStore] IsConfigured: True
[2021-10-29 14:38:20Z INFO ConfigurationManager] Is configured: True
[2021-10-29 14:38:20Z INFO ConfigurationManager] Settings Loaded
[2021-10-29 14:38:20Z INFO MessageListener] {
  "AcceptTeeEula": true,
  "AgentId": 101,
  "AgentName": "azure-pipelines-environment-agent-677c6c5d89-bc4mn",
  "PoolId": 28,
  "ServerUrl": "https://dev.azure.com/jbaconsulting/",
  "WorkFolder": "_work",
  "ProjectId": "9f91a63f-06b8-4e02-987b-e6b84d64dd8e",
  "EnvironmentId": 2,
  "EnvironmentVMResourceId": 25
}
[2021-10-29 14:38:20Z INFO Terminal] WRITE LINE: Scanning for tool capabilities.
[2021-10-29 14:38:20Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Capabilities.ICapabilitiesProvider'
[2021-10-29 14:38:20Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Capabilities.AgentCapabilitiesProvider, Microsoft.VisualStudio.Services.Agent
[2021-10-29 14:38:20Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Capabilities.EnvironmentCapabilitiesProvider, Microsoft.VisualStudio.Services.Agent
[2021-10-29 14:38:20Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Capabilities.NixCapabilitiesProvider, Microsoft.VisualStudio.Services.Agent
[2021-10-29 14:38:20Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Capabilities.UserCapabilitiesProvider, Microsoft.VisualStudio.Services.Agent
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Ignore: 'AZP_TOKEN'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Ignore: 'AZP_TOKEN_FILE'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Adding '_': '/azp/bin/Agent.Listener'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Adding 'AGENT_ALLOW_RUNASROOT': '1'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Adding 'AZP_ENVIRONMENT': 'NaFRA2 - Review Website'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Adding 'AZP_PROJECT': 'NaFRA2'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Adding 'AZP_URL': 'https://dev.azure.com/jbaconsulting/'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Adding 'DEBIAN_FRONTEND': 'noninteractive'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Adding 'HOME': '/root'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Adding 'HOSTNAME': 'azure-pipelines-environment-agent-677c6c5d89-bc4mn'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Adding 'KUBERNETES_PORT': 'tcp://172.20.0.1:443'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Adding 'KUBERNETES_PORT_443_TCP': 'tcp://172.20.0.1:443'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Adding 'KUBERNETES_PORT_443_TCP_ADDR': '172.20.0.1'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Adding 'KUBERNETES_PORT_443_TCP_PORT': '443'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Adding 'KUBERNETES_PORT_443_TCP_PROTO': 'tcp'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Adding 'KUBERNETES_SERVICE_HOST': '172.20.0.1'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Adding 'KUBERNETES_SERVICE_PORT': '443'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Adding 'KUBERNETES_SERVICE_PORT_HTTPS': '443'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPPROXY_PORT': 'tcp://172.20.204.73:80'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPPROXY_PORT_80_TCP': 'tcp://172.20.204.73:80'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPPROXY_PORT_80_TCP_ADDR': '172.20.204.73'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPPROXY_PORT_80_TCP_PORT': '80'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPPROXY_PORT_80_TCP_PROTO': 'tcp'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPPROXY_SERVICE_HOST': '172.20.204.73'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPPROXY_SERVICE_PORT': '80'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPSERVER_PORT': 'tcp://172.20.143.39:80'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPSERVER_PORT_80_TCP': 'tcp://172.20.143.39:80'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPSERVER_PORT_80_TCP_ADDR': '172.20.143.39'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPSERVER_PORT_80_TCP_PORT': '80'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPSERVER_PORT_80_TCP_PROTO': 'tcp'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPSERVER_SERVICE_HOST': '172.20.143.39'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPSERVER_SERVICE_PORT': '80'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Adding 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Adding 'PWD': '/azp'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Adding 'REVIEW_WEBSITE_PORT': 'tcp://172.20.218.41:80'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Adding 'REVIEW_WEBSITE_PORT_80_TCP': 'tcp://172.20.218.41:80'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Adding 'REVIEW_WEBSITE_PORT_80_TCP_ADDR': '172.20.218.41'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Adding 'REVIEW_WEBSITE_PORT_80_TCP_PORT': '80'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Adding 'REVIEW_WEBSITE_PORT_80_TCP_PROTO': 'tcp'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Adding 'REVIEW_WEBSITE_SERVICE_HOST': '172.20.218.41'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Adding 'REVIEW_WEBSITE_SERVICE_PORT': '80'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Skipping: 'SHLVL'
[2021-10-29 14:38:20Z INFO EnvironmentCapabilitiesProvider] Adding 'VSO_AGENT_IGNORE': 'AZP_TOKEN,AZP_TOKEN_FILE'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Which: 'android'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Checking file: 'tools/android'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Checking file: '/root/Library/Developer/Xamarin/android-sdk-macosx/tools/android'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Which: 'ant'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Which: 'waagent'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Which: 'bundle'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Which: 'clang'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Which: 'cmake'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Which: 'curl'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Location: '{matches.First()}'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Adding 'curl': '/usr/bin/curl'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Which: 'docker'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Which: 'dotnet'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Which: 'git'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Location: '{matches.First()}'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Adding 'git': '/usr/bin/git'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Which: 'gulp'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Which: 'java'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Which: 'javac'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Which: 'make'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Which: 'mvn'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Which: 'xbuild'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Checking file: '/Library/Frameworks/Mono.framework/Commands/xbuild'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Which: 'msbuild'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Checking file: '/Library/Frameworks/Mono.framework/Commands/msbuild'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Which: 'node'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Which: 'nodejs'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Which: 'npm'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Which: 'python'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Which: 'python3'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Location: '{matches.First()}'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Adding 'python3': '/usr/bin/python3'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Which: 'sh'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Location: '{matches.First()}'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Adding 'sh': '/bin/sh'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Which: 'svn'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Which: 'ruby'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Which: 'rake'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Which: 'svn'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Which: 'mdtool'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Checking file: '/Applications/Xamarin Studio.app/Contents/MacOS/mdtool'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Checking file: '/Applications/Visual Studio.app/Contents/MacOS/vstool'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Which: 'generator'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Checking file: '/Library/Frameworks/Xamarin.Android.framework/Commands/generator'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Checking file: '/Library/Frameworks/Xamarin.Android.framework/Versions/Current/Version'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Which: 'xcode-select'
[2021-10-29 14:38:20Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 14:38:20Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 14:38:20Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 14:38:20Z INFO AgentCapabilitiesProvider] Adding 'Agent.Name': 'azure-pipelines-environment-agent-677c6c5d89-bc4mn'
[2021-10-29 14:38:20Z INFO AgentCapabilitiesProvider] Adding 'Agent.OS': 'Linux'
[2021-10-29 14:38:20Z INFO AgentCapabilitiesProvider] Adding 'Agent.OSArchitecture': 'X64'
[2021-10-29 14:38:20Z INFO AgentCapabilitiesProvider] Adding 'InteractiveSession': 'True'
[2021-10-29 14:38:20Z INFO AgentCapabilitiesProvider] Adding 'Agent.Version': '2.185.1'
[2021-10-29 14:38:20Z INFO AgentCapabilitiesProvider] Adding 'Agent.ComputerName': 'azure-pipelines-environment-agent-677c6c5d89-bc4mn'
[2021-10-29 14:38:20Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 14:38:20Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 14:38:20Z INFO AgentCapabilitiesProvider] Adding 'Agent.HomeDirectory': '/azp'
[2021-10-29 14:38:20Z INFO MessageListener] Loading Credentials
[2021-10-29 14:38:20Z INFO ConfigurationStore] HasCredentials()
[2021-10-29 14:38:20Z INFO ConfigurationStore] stored True
[2021-10-29 14:38:20Z INFO CredentialManager] GetCredentialProvider
[2021-10-29 14:38:20Z INFO CredentialManager] Creating type OAuth
[2021-10-29 14:38:20Z INFO CredentialManager] Creating credential type: OAuth
[2021-10-29 14:38:20Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 14:38:20Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 14:38:20Z INFO HostContext] Well known config file 'RSACredentials': '/azp/.credentials_rsaparams'
[2021-10-29 14:38:20Z INFO RSAFileKeyManager] Loading RSA key parameters from file /azp/.credentials_rsaparams
[2021-10-29 14:38:20Z INFO Terminal] WRITE LINE: Connecting to the server.
[2021-10-29 14:38:20Z INFO MessageListener] Attempt to create session.
[2021-10-29 14:38:20Z INFO MessageListener] Connecting to the Agent Server...
[2021-10-29 14:38:20Z INFO AgentServer] Establish connection with 100 seconds timeout.
[2021-10-29 14:38:20Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2021-10-29 14:38:20Z WARN VisualStudioServices] Authentication failed with status code 401.
Cache-Control: no-cache
Pragma: no-cache
P3P: CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
WWW-Authenticate: Bearer authorization_uri=https://login.microsoftonline.com/3131e85c-e560-4bb3-a82f-8b339ad41833, Basic realm="https://tfsprodweusu4.app.visualstudio.com/", TFS-Federated
X-TFS-ProcessId: ab8f28b2-f0b8-4872-978e-9cfeb29b0245
Strict-Transport-Security: max-age=31536000; includeSubDomains
ActivityId: 40091f41-8f6f-48c5-bfce-7e172c7b67af
X-TFS-Session: 72280435-e382-494f-851e-99d95378f54f
X-VSS-E2EID: 902da19f-b3e0-4372-bfae-cb452617f93b
X-VSS-SenderDeploymentId: 3dbbfbca-3f3a-b896-0b3a-ea9e2087c7ac
X-Frame-Options: SAMEORIGIN
X-TFS-FedAuthRealm: https://tfsprodweusu4.app.visualstudio.com/
X-TFS-FedAuthIssuer: https://dev.azure.com/jbaconsulting/
X-VSS-AuthorizationEndpoint: https://vssps.dev.azure.com/jbaconsulting/
X-VSS-ResourceTenant: 3131e85c-e560-4bb3-a82f-8b339ad41833
X-VSS-S2STargetService: 00000002-0000-8888-8000-000000000000/visualstudio.com
X-TFS-FedAuthRedirect: https://spsprodweu2.vssps.visualstudio.com/_signin?realm=dev.azure.com&reply_to=https%3A%2F%2Fdev.azure.com%2Fjbaconsulting%2F_apis%2FconnectionData%3FconnectOptions%3D0%26lastChangeId%3D330326078%26lastChangeId64%3D330326078&redirect=1&hid=e8357ffe-403f-41bc-aae2-5d67ba1a7daa&context=eyJodCI6MiwiaGlkIjoiN2U4ZGZmYWUtYTA2Yy00MzI1LWE4MWQtZGE1NmY5ZTg5YjY4IiwicXMiOnt9LCJyciI6IiIsInZoIjoiIiwiY3YiOiIiLCJjcyI6IiJ90#ctx=eyJTaWduSW5Db29raWVEb21haW5zIjpbImh0dHBzOi8vbG9naW4ubWljcm9zb2Z0b25saW5lLmNvbSIsImh0dHBzOi8vbG9naW4ubWljcm9zb2Z0b25saW5lLmNvbSJdfQ2
Request-Context: appId=cid-v1:3142c212-5102-492c-94e2-153eb747f4c0
Access-Control-Expose-Headers: Request-Context
X-Content-Type-Options: nosniff
X-Cache: CONFIG_NOCACHE
X-MSEdge-Ref: Ref A: 3F7A57CB16DC498C9D740C4F34A739C5 Ref B: LTSEDGE0908 Ref C: 2021-10-29T14:38:20Z
Date: Fri, 29 Oct 2021 14:38:20 GMT

[2021-10-29 14:38:20Z INFO RSAFileKeyManager] Loading RSA key parameters from file /azp/.credentials_rsaparams
[2021-10-29 14:38:20Z INFO RSAFileKeyManager] Loading RSA key parameters from file /azp/.credentials_rsaparams
[2021-10-29 14:38:20Z INFO VisualStudioServices] AAD Correlation ID for this token request: Unknown
[2021-10-29 14:38:20Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2021-10-29 14:38:20Z INFO AgentServer] Establish connection with 60 seconds timeout.
[2021-10-29 14:38:20Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2021-10-29 14:38:20Z INFO AgentServer] Establish connection with 60 seconds timeout.
[2021-10-29 14:38:20Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2021-10-29 14:38:20Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2021-10-29 14:38:20Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2021-10-29 14:38:21Z INFO MessageListener] VssConnection created
[2021-10-29 14:38:21Z INFO MessageListener] Session created.
[2021-10-29 14:38:21Z INFO Terminal] WRITE LINE: 2021-10-29 14:38:21Z: Listening for Jobs
[2021-10-29 14:38:21Z INFO JobDispatcher] Set agent/worker IPC timeout to 30 seconds.
[2021-10-29 15:04:57Z INFO RSAFileKeyManager] Loading RSA key parameters from file /azp/.credentials_rsaparams
[2021-10-29 15:04:57Z INFO MessageListener] Message '1' received from session '6118f93f-64b0-4dca-a23a-7eee730a45c5'.
[2021-10-29 15:04:57Z INFO Agent] Refresh message received, kick-off selfupdate background process.
[2021-10-29 15:04:57Z INFO SelfUpdater] Version '2.194.0' of 'agent' package available in server.
[2021-10-29 15:04:57Z INFO SelfUpdater] Current running agent version is 2.185.1
[2021-10-29 15:04:57Z INFO SelfUpdater] An update is available.
[2021-10-29 15:04:57Z INFO Terminal] WRITE LINE: Agent update in progress, do not shutdown agent.
[2021-10-29 15:04:57Z INFO Terminal] WRITE LINE: Downloading 2.194.0 agent
[2021-10-29 15:04:57Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 15:04:57Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:04:57Z INFO HostContext] Well known directory 'Work': '/azp/_work'
[2021-10-29 15:04:57Z INFO SelfUpdater] Attempt 1: save latest agent into /azp/_work/_update/agent1.tar.gz.
[2021-10-29 15:04:57Z INFO SelfUpdater] Download agent: begin download
[2021-10-29 15:04:58Z INFO SelfUpdater] Download agent: finished download
[2021-10-29 15:04:58Z INFO SelfUpdater] Which: 'tar'
[2021-10-29 15:04:58Z INFO SelfUpdater] Location: '{matches.First()}'
[2021-10-29 15:04:58Z INFO ProcessInvokerWrapper] Starting process:
[2021-10-29 15:04:58Z INFO ProcessInvokerWrapper]   File name: '/bin/tar'
[2021-10-29 15:04:58Z INFO ProcessInvokerWrapper]   Arguments: '-xzf "/azp/_work/_update/agent1.tar.gz"'
[2021-10-29 15:04:58Z INFO ProcessInvokerWrapper]   Working directory: '/azp/_work/_update'
[2021-10-29 15:04:58Z INFO ProcessInvokerWrapper]   Require exit code zero: 'False'
[2021-10-29 15:04:58Z INFO ProcessInvokerWrapper]   Encoding web name:  ; code page: ''
[2021-10-29 15:04:58Z INFO ProcessInvokerWrapper]   Force kill process on cancellation: 'False'
[2021-10-29 15:04:58Z INFO ProcessInvokerWrapper]   Redirected STDIN: 'False'
[2021-10-29 15:04:58Z INFO ProcessInvokerWrapper]   Persist current code page: 'False'
[2021-10-29 15:04:58Z INFO ProcessInvokerWrapper]   Keep redirected STDIN open: 'False'
[2021-10-29 15:04:58Z INFO ProcessInvokerWrapper]   High priority process: 'False'
[2021-10-29 15:04:58Z INFO ProcessInvokerWrapper] Failed to update oom_score_adj for PID: 274.
[2021-10-29 15:04:58Z INFO ProcessInvokerWrapper] System.UnauthorizedAccessException: Access to the path '/proc/274/oom_score_adj' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.FlushWriteBuffer()
   at System.IO.FileStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.StreamWriter.CloseStreamFromDispose(Boolean disposing)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at System.IO.File.WriteAllText(String path, String contents)
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.WriteProcessOomScoreAdj(Int32 processId, Int32 oomScoreAdj)
[2021-10-29 15:04:58Z INFO ProcessInvokerWrapper] Process started with process id 274, waiting for process exit.
[2021-10-29 15:04:59Z INFO RSAFileKeyManager] Loading RSA key parameters from file /azp/.credentials_rsaparams
[2021-10-29 15:04:59Z INFO MessageListener] Message '2' received from session '6118f93f-64b0-4dca-a23a-7eee730a45c5'.
[2021-10-29 15:04:59Z INFO Agent] Skip message deletion for job request message '2'.
[2021-10-29 15:05:00Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2021-10-29 15:05:00Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2021-10-29 15:05:00Z INFO ProcessInvokerWrapper] Exited process 274 with exit code 0
[2021-10-29 15:05:00Z INFO ProcessInvokerWrapper] Finished process 274 with exit code 0, and elapsed time 00:00:02.0989637.
[2021-10-29 15:05:00Z INFO SelfUpdater] Finished getting latest agent package at: /azp/_work/_update.
[2021-10-29 15:05:00Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 15:05:00Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:00Z INFO SelfUpdater] Copy /azp/_work/_update/bin to /azp/bin.2.194.0.
[2021-10-29 15:05:00Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 15:05:00Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:00Z INFO SelfUpdater] Copy /azp/_work/_update/externals to /azp/externals.2.194.0.
[2021-10-29 15:05:01Z INFO SelfUpdater] Copy any remaining .sh/.cmd files into agent root.
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:01Z INFO SelfUpdater] Download latest agent and unzip into agent root.
[2021-10-29 15:05:01Z INFO Terminal] WRITE LINE: Waiting for current job finish running.
[2021-10-29 15:05:01Z INFO SelfUpdater] All running jobs have exited.
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:01Z INFO SelfUpdater] Delete old version agent backup.
[2021-10-29 15:05:01Z INFO Terminal] WRITE LINE: Generate and execute update script.
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Diag': '/azp/_diag'
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Work': '/azp/_work'
[2021-10-29 15:05:01Z INFO SelfUpdater] Generate update script into: /azp/_work/_update.sh
[2021-10-29 15:05:01Z INFO SelfUpdater] Which: 'bash'
[2021-10-29 15:05:01Z INFO SelfUpdater] Location: '{matches.First()}'
[2021-10-29 15:05:01Z INFO SelfUpdater] Update script start running
[2021-10-29 15:05:01Z INFO Terminal] WRITE LINE: Agent will exit shortly for update, should back online within 10 seconds.
[2021-10-29 15:05:01Z INFO Agent] Auto update task finished at backend, an agent update is ready to apply exit the current agent instance.
[2021-10-29 15:05:01Z INFO Agent] Stop message queue looping.
[2021-10-29 15:05:01Z WARN VisualStudioServices] GET request to https://dev.azure.com/jbaconsulting/_apis/distributedtask/pools/28/messages?sessionId=6118f93f-64b0-4dca-a23a-7eee730a45c5&lastMessageId=2 has been cancelled.
[2021-10-29 15:05:01Z INFO MessageListener] Get next message has been cancelled.
[2021-10-29 15:05:01Z INFO Agent] Ignore any exception after cancel message loop. System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillBufferAsync>g__InternalFillBufferAsync|215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Listener.MessageListener.GetNextMessageAsync(CancellationToken token)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.RunAsync(AgentSettings settings, Boolean runOnce)
[2021-10-29 15:05:01Z INFO JobDispatcher] Shutting down JobDispatcher. Make sure all WorkerDispatcher has finished.
[2021-10-29 15:05:01Z INFO AgentProcess] Agent package linux-x64.
[2021-10-29 15:05:01Z INFO AgentProcess] Running on Linux (X64).
[2021-10-29 15:05:01Z INFO AgentProcess] RuntimeInformation: Linux 5.4.149-73.259.amzn2.x86_64 #1 SMP Mon Sep 27 12:48:12 UTC 2021.
[2021-10-29 15:05:01Z INFO AgentProcess] Version: 2.185.1
[2021-10-29 15:05:01Z INFO AgentProcess] Commit: 45c52d01eec6c18e3a3e5d8e2a4859fbfc90eff7
[2021-10-29 15:05:01Z INFO AgentProcess] Culture: 
[2021-10-29 15:05:01Z INFO AgentProcess] UI Culture: 
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:01Z INFO AgentProcess] Validating directory permissions for: '/azp'
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:01Z INFO CommandSettings] Remove {
  "Auth": "PAT",
  "LaunchBrowser": false,
  "Password": null,
  "Token": "***",
  "Unattended": true,
  "UserName": null,
  "Help": false,
  "Version": false
}
[2021-10-29 15:05:01Z INFO AgentProcess] Arguments parsed
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:01Z INFO HostContext] Well known config file 'Proxy': '/azp/.proxy'
[2021-10-29 15:05:01Z INFO VstsAgentWebProxy] No proxy setting found.
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:01Z INFO HostContext] Well known config file 'Certificates': '/azp/.certificates'
[2021-10-29 15:05:01Z INFO AgentCertificateManager] No certificate setting found.
[2021-10-29 15:05:01Z INFO Agent] ExecuteCommand
[2021-10-29 15:05:01Z INFO ConfigurationStore] currentAssemblyLocation: /azp/bin/Agent.Listener.dll
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 15:05:01Z INFO ConfigurationStore] binPath: /azp/bin
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:01Z INFO ConfigurationStore] RootFolder: /azp
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:01Z INFO HostContext] Well known config file 'Agent': '/azp/.agent'
[2021-10-29 15:05:01Z INFO ConfigurationStore] ConfigFilePath: /azp/.agent
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:01Z INFO HostContext] Well known config file 'Credentials': '/azp/.credentials'
[2021-10-29 15:05:01Z INFO ConfigurationStore] CredFilePath: /azp/.credentials
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:01Z INFO HostContext] Well known config file 'Service': '/azp/.service'
[2021-10-29 15:05:01Z INFO ConfigurationStore] ServiceConfigFilePath: /azp/.service
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:01Z INFO HostContext] Well known config file 'Autologon': '/azp/.autologon'
[2021-10-29 15:05:01Z INFO ConfigurationStore] AutoLogonSettingsFilePath: /azp/.autologon
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:01Z INFO HostContext] Well known config file 'Options': '/azp/.options'
[2021-10-29 15:05:01Z INFO ConfigurationStore] RuntimeOptionsFilePath: /azp/.options
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Bin': '/azp/bin'
[2021-10-29 15:05:01Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:01Z INFO HostContext] Well known config file 'SetupInfo': '/azp/.setup_info'
[2021-10-29 15:05:01Z INFO ConfigurationStore] SetupInfoFilePath: /azp/.setup_info
[2021-10-29 15:05:01Z INFO ConfigurationStore] IsServiceConfigured()
[2021-10-29 15:05:01Z INFO ConfigurationStore] IsServiceConfigured: False
[2021-10-29 15:05:02Z INFO Terminal] WRITE LINE: Removing agent from the server
[2021-10-29 15:05:02Z INFO ConfigurationStore] IsConfigured()
[2021-10-29 15:05:02Z INFO ConfigurationStore] IsConfigured: True
[2021-10-29 15:05:02Z INFO ConfigurationStore] HasCredentials()
[2021-10-29 15:05:02Z INFO ConfigurationStore] stored True
[2021-10-29 15:05:02Z INFO ConfigurationStore] Read setting file: 320 chars
[2021-10-29 15:05:02Z INFO ConfigurationManager] GetCredentialProvider
[2021-10-29 15:05:02Z INFO CommandSettings] Arg 'auth': 'PAT'
[2021-10-29 15:05:02Z INFO ConfigurationManager] Creating credential for auth: PAT
[2021-10-29 15:05:02Z INFO CredentialManager] GetCredentialProvider
[2021-10-29 15:05:02Z INFO CredentialManager] Creating type PAT
[2021-10-29 15:05:02Z INFO CredentialManager] Creating credential type: PAT
[2021-10-29 15:05:02Z INFO PersonalAccessToken] EnsureCredential
[2021-10-29 15:05:02Z INFO CommandSettings] Arg 'token': '***'
[2021-10-29 15:05:02Z INFO PersonalAccessToken] GetVssCredentials
[2021-10-29 15:05:02Z INFO PersonalAccessToken] token retrieved: 52 chars
[2021-10-29 15:05:02Z INFO PersonalAccessToken] cred created
[2021-10-29 15:05:02Z INFO ConfigurationManager] cred retrieved
[2021-10-29 15:05:02Z INFO ConfigurationManager] Agent configured for deploymentGroup : False
[2021-10-29 15:05:02Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Listener.Configuration.IConfigurationProvider'
[2021-10-29 15:05:02Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.BuildReleasesAgentConfigProvider, Agent.Listener
[2021-10-29 15:05:02Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.DeploymentGroupAgentConfigProvider, Agent.Listener
[2021-10-29 15:05:02Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.SharedDeploymentAgentConfigProvider, Agent.Listener
[2021-10-29 15:05:02Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.EnvironmentVMResourceConfigProvider, Agent.Listener
[2021-10-29 15:05:02Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2021-10-29 15:05:02Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2021-10-29 15:05:02Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2021-10-29 15:05:02Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2021-10-29 15:05:02Z INFO ConfigurationManager] Server deployment type: Hosted
[2021-10-29 15:05:02Z INFO Terminal] WRITE LINE: Connecting to server ...
[2021-10-29 15:05:02Z INFO EnvironmentVMResourceConfigProvider] Test connection with environment
[2021-10-29 15:05:02Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2021-10-29 15:05:02Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2021-10-29 15:05:02Z INFO EnvironmentVMResourceConfigProvider] Connection complete for environment
[2021-10-29 15:05:02Z INFO EnvironmentVMResourceConfigProvider] Deleting environment virtual machine resource with id: '25'
[2021-10-29 15:05:02Z ERR  VisualStudioServices] DELETE request to https://dev.azure.com/jbaconsulting/9f91a63f-06b8-4e02-987b-e6b84d64dd8e/_apis/pipelines/environments/2/providers/virtualmachines/25 failed. HTTP Status: InternalServerError, AFD Ref: Ref A: 89C7FD16859B4175BC1D45A8E25EDC88 Ref B: LON04EDGE1118 Ref C: 2021-10-29T15:05:02Z
[2021-10-29 15:05:02Z INFO Terminal] WRITE LINE: Failed: Removing agent from the server
[2021-10-29 15:05:02Z ERR  Agent] Microsoft.TeamFoundation.DistributedTask.WebApi.TaskAgentJobStillRunningException: Agent "azure-pipelines-environment-agent-677c6c5d89-bc4mn" is running a job for pool "environment-2-f642640a-3d5c-4896-8fed-0b46ef1c29f6"
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpMethod method, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   at Microsoft.Azure.Pipelines.Environments.WebApi.EnvironmentsHttpClientBase.DeleteVirtualMachineResourceAsync(Guid project, Int32 environmentId, Int32 resourceId, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.EnvironmentVMResourceConfigProvider.DeleteAgentAsync(AgentSettings agentSettings)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.UnconfigureAsync(CommandSettings command)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.ExecuteCommand(CommandSettings command)
[2021-10-29 15:05:02Z ERR  Terminal] WRITE ERROR: Agent "azure-pipelines-environment-agent-677c6c5d89-bc4mn" is running a job for pool "environment-2-f642640a-3d5c-4896-8fed-0b46ef1c29f6"
[2021-10-29 15:05:04Z INFO AgentProcess] Agent package linux-x64.
[2021-10-29 15:05:04Z INFO AgentProcess] Running on Linux (X64).
[2021-10-29 15:05:04Z INFO AgentProcess] RuntimeInformation: Linux 5.4.149-73.259.amzn2.x86_64 #1 SMP Mon Sep 27 12:48:12 UTC 2021.
[2021-10-29 15:05:04Z INFO AgentProcess] Version: 2.194.0
[2021-10-29 15:05:04Z INFO AgentProcess] Commit: 7dbde4ca1590dc331acd879fb240c5428268b30d
[2021-10-29 15:05:04Z INFO AgentProcess] Culture: 
[2021-10-29 15:05:04Z INFO AgentProcess] UI Culture: 
[2021-10-29 15:05:04Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:04Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:04Z INFO AgentProcess] Validating directory permissions for: '/azp'
[2021-10-29 15:05:04Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:04Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:04Z INFO CommandSettings] Run {
  "Commit": false,
  "Diagnostics": false,
  "RunOnce": false,
  "StartupType": null,
  "Help": false,
  "Version": false
}
[2021-10-29 15:05:04Z INFO AgentProcess] Arguments parsed
[2021-10-29 15:05:04Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:04Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:04Z INFO HostContext] Well known config file 'Proxy': '/azp/.proxy'
[2021-10-29 15:05:04Z INFO VstsAgentWebProxy] No proxy setting found.
[2021-10-29 15:05:04Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:04Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:04Z INFO HostContext] Well known config file 'Certificates': '/azp/.certificates'
[2021-10-29 15:05:04Z INFO AgentCertificateManager] No certificate setting found.
[2021-10-29 15:05:04Z INFO Agent] ExecuteCommand
[2021-10-29 15:05:04Z INFO ConfigurationStore] currentAssemblyLocation: /azp/bin.2.194.0/Agent.Listener.dll
[2021-10-29 15:05:04Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:04Z INFO ConfigurationStore] binPath: /azp/bin.2.194.0
[2021-10-29 15:05:04Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:04Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:04Z INFO ConfigurationStore] RootFolder: /azp
[2021-10-29 15:05:04Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:04Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:04Z INFO HostContext] Well known config file 'Agent': '/azp/.agent'
[2021-10-29 15:05:04Z INFO ConfigurationStore] ConfigFilePath: /azp/.agent
[2021-10-29 15:05:04Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:04Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:04Z INFO HostContext] Well known config file 'Credentials': '/azp/.credentials'
[2021-10-29 15:05:04Z INFO ConfigurationStore] CredFilePath: /azp/.credentials
[2021-10-29 15:05:04Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:04Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:04Z INFO HostContext] Well known config file 'Service': '/azp/.service'
[2021-10-29 15:05:04Z INFO ConfigurationStore] ServiceConfigFilePath: /azp/.service
[2021-10-29 15:05:04Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:04Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:04Z INFO HostContext] Well known config file 'Autologon': '/azp/.autologon'
[2021-10-29 15:05:04Z INFO ConfigurationStore] AutoLogonSettingsFilePath: /azp/.autologon
[2021-10-29 15:05:04Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:04Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:04Z INFO HostContext] Well known config file 'Options': '/azp/.options'
[2021-10-29 15:05:04Z INFO ConfigurationStore] RuntimeOptionsFilePath: /azp/.options
[2021-10-29 15:05:04Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:04Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:04Z INFO HostContext] Well known config file 'SetupInfo': '/azp/.setup_info'
[2021-10-29 15:05:04Z INFO ConfigurationStore] SetupInfoFilePath: /azp/.setup_info
[2021-10-29 15:05:04Z INFO ConfigurationManager] LoadSettings
[2021-10-29 15:05:04Z INFO ConfigurationStore] IsConfigured()
[2021-10-29 15:05:04Z INFO ConfigurationStore] IsConfigured: True
[2021-10-29 15:05:04Z INFO ConfigurationManager] Is configured: True
[2021-10-29 15:05:04Z INFO ConfigurationStore] Read setting file: 320 chars
[2021-10-29 15:05:04Z INFO ConfigurationManager] Settings Loaded
[2021-10-29 15:05:04Z INFO ConfigurationStore] IsServiceConfigured()
[2021-10-29 15:05:04Z INFO ConfigurationStore] IsServiceConfigured: False
[2021-10-29 15:05:04Z INFO ConfigurationStore] IsConfigured()
[2021-10-29 15:05:04Z INFO ConfigurationStore] IsConfigured: True
[2021-10-29 15:05:04Z INFO ConfigurationManager] Is configured: True
[2021-10-29 15:05:04Z INFO Agent] Could not parse the argument value '' for StartupType. Defaulting to Manual
[2021-10-29 15:05:04Z INFO Agent] Set agent startup type - Manual
[2021-10-29 15:05:04Z INFO CommandSettings] Flag 'once': 'False'
[2021-10-29 15:05:04Z INFO CommandSettings] Flag 'once': 'False'
[2021-10-29 15:05:04Z INFO Agent] RunAsync
[2021-10-29 15:05:04Z INFO ConfigurationManager] LoadSettings
[2021-10-29 15:05:04Z INFO ConfigurationStore] IsConfigured()
[2021-10-29 15:05:04Z INFO ConfigurationStore] IsConfigured: True
[2021-10-29 15:05:04Z INFO ConfigurationManager] Is configured: True
[2021-10-29 15:05:04Z INFO ConfigurationManager] Settings Loaded
[2021-10-29 15:05:04Z INFO MessageListener] {
  "AcceptTeeEula": true,
  "AgentId": 101,
  "AgentName": "azure-pipelines-environment-agent-677c6c5d89-bc4mn",
  "PoolId": 28,
  "ServerUrl": "https://dev.azure.com/jbaconsulting/",
  "WorkFolder": "_work",
  "ProjectId": "9f91a63f-06b8-4e02-987b-e6b84d64dd8e",
  "EnvironmentId": 2,
  "EnvironmentVMResourceId": 25
}
[2021-10-29 15:05:04Z INFO Terminal] WRITE LINE: Scanning for tool capabilities.
[2021-10-29 15:05:04Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Capabilities.ICapabilitiesProvider'
[2021-10-29 15:05:04Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Capabilities.AgentCapabilitiesProvider, Microsoft.VisualStudio.Services.Agent
[2021-10-29 15:05:04Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Capabilities.EnvironmentCapabilitiesProvider, Microsoft.VisualStudio.Services.Agent
[2021-10-29 15:05:04Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Capabilities.NixCapabilitiesProvider, Microsoft.VisualStudio.Services.Agent
[2021-10-29 15:05:04Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Capabilities.UserCapabilitiesProvider, Microsoft.VisualStudio.Services.Agent
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Ignore: 'AZP_TOKEN'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Ignore: 'AZP_TOKEN_FILE'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Adding '_': '/azp/bin/Agent.Listener'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Adding 'AGENT_ALLOW_RUNASROOT': '1'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Adding 'AZP_ENVIRONMENT': 'NaFRA2 - Review Website'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Adding 'AZP_PROJECT': 'NaFRA2'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Adding 'AZP_URL': 'https://dev.azure.com/jbaconsulting/'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Adding 'DEBIAN_FRONTEND': 'noninteractive'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Adding 'HOME': '/root'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Adding 'HOSTNAME': 'azure-pipelines-environment-agent-677c6c5d89-bc4mn'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Adding 'KUBERNETES_PORT': 'tcp://172.20.0.1:443'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Adding 'KUBERNETES_PORT_443_TCP': 'tcp://172.20.0.1:443'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Adding 'KUBERNETES_PORT_443_TCP_ADDR': '172.20.0.1'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Adding 'KUBERNETES_PORT_443_TCP_PORT': '443'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Adding 'KUBERNETES_PORT_443_TCP_PROTO': 'tcp'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Adding 'KUBERNETES_SERVICE_HOST': '172.20.0.1'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Adding 'KUBERNETES_SERVICE_PORT': '443'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Adding 'KUBERNETES_SERVICE_PORT_HTTPS': '443'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPPROXY_PORT': 'tcp://172.20.204.73:80'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPPROXY_PORT_80_TCP': 'tcp://172.20.204.73:80'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPPROXY_PORT_80_TCP_ADDR': '172.20.204.73'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPPROXY_PORT_80_TCP_PORT': '80'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPPROXY_PORT_80_TCP_PROTO': 'tcp'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPPROXY_SERVICE_HOST': '172.20.204.73'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPPROXY_SERVICE_PORT': '80'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPSERVER_PORT': 'tcp://172.20.143.39:80'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPSERVER_PORT_80_TCP': 'tcp://172.20.143.39:80'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPSERVER_PORT_80_TCP_ADDR': '172.20.143.39'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPSERVER_PORT_80_TCP_PORT': '80'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPSERVER_PORT_80_TCP_PROTO': 'tcp'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPSERVER_SERVICE_HOST': '172.20.143.39'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPSERVER_SERVICE_PORT': '80'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Adding 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Adding 'PWD': '/azp'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Adding 'REVIEW_WEBSITE_PORT': 'tcp://172.20.218.41:80'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Adding 'REVIEW_WEBSITE_PORT_80_TCP': 'tcp://172.20.218.41:80'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Adding 'REVIEW_WEBSITE_PORT_80_TCP_ADDR': '172.20.218.41'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Adding 'REVIEW_WEBSITE_PORT_80_TCP_PORT': '80'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Adding 'REVIEW_WEBSITE_PORT_80_TCP_PROTO': 'tcp'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Adding 'REVIEW_WEBSITE_SERVICE_HOST': '172.20.218.41'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Adding 'REVIEW_WEBSITE_SERVICE_PORT': '80'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Skipping: 'SHLVL'
[2021-10-29 15:05:04Z INFO EnvironmentCapabilitiesProvider] Adding 'VSO_AGENT_IGNORE': 'AZP_TOKEN,AZP_TOKEN_FILE'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Which: 'android'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Checking file: 'tools/android'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Checking file: '/root/Library/Developer/Xamarin/android-sdk-macosx/tools/android'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Which: 'ant'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Which: 'waagent'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Which: 'bundle'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Which: 'clang'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Which: 'cmake'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Which: 'curl'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Location: '{matches.First()}'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Adding 'curl': '/usr/bin/curl'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Which: 'docker'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Which: 'dotnet'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Which: 'git'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Location: '{matches.First()}'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Adding 'git': '/usr/bin/git'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Which: 'gulp'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Which: 'java'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Which: 'javac'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Which: 'make'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Which: 'mvn'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Which: 'xbuild'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Checking file: '/Library/Frameworks/Mono.framework/Commands/xbuild'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Which: 'msbuild'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Checking file: '/Library/Frameworks/Mono.framework/Commands/msbuild'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Which: 'node'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Which: 'nodejs'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Which: 'npm'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Which: 'python'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Which: 'python3'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Location: '{matches.First()}'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Adding 'python3': '/usr/bin/python3'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Which: 'sh'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Location: '{matches.First()}'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Adding 'sh': '/bin/sh'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Which: 'svn'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Which: 'ruby'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Which: 'rake'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Which: 'svn'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Which: 'mdtool'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Checking file: '/Applications/Xamarin Studio.app/Contents/MacOS/mdtool'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Checking file: '/Applications/Visual Studio.app/Contents/MacOS/vstool'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Which: 'generator'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Checking file: '/Library/Frameworks/Xamarin.Android.framework/Commands/generator'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Checking file: '/Library/Frameworks/Xamarin.Android.framework/Versions/Current/Version'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Which: 'xcode-select'
[2021-10-29 15:05:04Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:04Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:04Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:04Z INFO AgentCapabilitiesProvider] Adding 'Agent.Name': 'azure-pipelines-environment-agent-677c6c5d89-bc4mn'
[2021-10-29 15:05:04Z INFO AgentCapabilitiesProvider] Adding 'Agent.OS': 'Linux'
[2021-10-29 15:05:04Z INFO AgentCapabilitiesProvider] Adding 'Agent.OSArchitecture': 'X64'
[2021-10-29 15:05:04Z INFO AgentCapabilitiesProvider] Adding 'InteractiveSession': 'True'
[2021-10-29 15:05:04Z INFO AgentCapabilitiesProvider] Adding 'Agent.Version': '2.194.0'
[2021-10-29 15:05:04Z INFO AgentCapabilitiesProvider] Adding 'Agent.ComputerName': 'azure-pipelines-environment-agent-677c6c5d89-bc4mn'
[2021-10-29 15:05:04Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:04Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:04Z INFO AgentCapabilitiesProvider] Adding 'Agent.HomeDirectory': '/azp'
[2021-10-29 15:05:04Z INFO MessageListener] Loading Credentials
[2021-10-29 15:05:04Z INFO ConfigurationStore] HasCredentials()
[2021-10-29 15:05:04Z INFO ConfigurationStore] stored True
[2021-10-29 15:05:04Z INFO CredentialManager] GetCredentialProvider
[2021-10-29 15:05:04Z INFO CredentialManager] Creating type OAuth
[2021-10-29 15:05:04Z INFO CredentialManager] Creating credential type: OAuth
[2021-10-29 15:05:04Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:04Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:04Z INFO HostContext] Well known config file 'RSACredentials': '/azp/.credentials_rsaparams'
[2021-10-29 15:05:04Z INFO RSAFileKeyManager] Loading RSA key parameters from file /azp/.credentials_rsaparams
[2021-10-29 15:05:04Z INFO Terminal] WRITE LINE: Connecting to the server.
[2021-10-29 15:05:04Z INFO MessageListener] Attempt to create session.
[2021-10-29 15:05:04Z INFO MessageListener] Connecting to the Agent Server...
[2021-10-29 15:05:04Z INFO AgentServer] Establish connection with 100 seconds timeout.
[2021-10-29 15:05:05Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2021-10-29 15:05:05Z WARN VisualStudioServices] Authentication failed with status code 401.
Cache-Control: no-cache
Pragma: no-cache
P3P: CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
WWW-Authenticate: Bearer authorization_uri=https://login.microsoftonline.com/3131e85c-e560-4bb3-a82f-8b339ad41833, Basic realm="https://tfsprodweusu4.app.visualstudio.com/", TFS-Federated
X-TFS-ProcessId: e7e9ab58-f3cb-4093-b6db-e2f7e5981d19
Strict-Transport-Security: max-age=31536000; includeSubDomains
ActivityId: f78ece2e-77c3-4da5-a943-1e5eb61f0e3a
X-TFS-Session: 855a1b02-773a-4a85-955f-cefdea2359e7
X-VSS-E2EID: 877ff060-5238-4a23-8abb-9a7cbdf989b4
X-VSS-SenderDeploymentId: 3dbbfbca-3f3a-b896-0b3a-ea9e2087c7ac
X-Frame-Options: SAMEORIGIN
X-TFS-FedAuthRealm: https://tfsprodweusu4.app.visualstudio.com/
X-TFS-FedAuthIssuer: https://dev.azure.com/jbaconsulting/
X-VSS-AuthorizationEndpoint: https://vssps.dev.azure.com/jbaconsulting/
X-VSS-ResourceTenant: 3131e85c-e560-4bb3-a82f-8b339ad41833
X-VSS-S2STargetService: 00000002-0000-8888-8000-000000000000/visualstudio.com
X-TFS-FedAuthRedirect: https://spsprodweu2.vssps.visualstudio.com/_signin?realm=dev.azure.com&reply_to=https%3A%2F%2Fdev.azure.com%2Fjbaconsulting%2F_apis%2FconnectionData%3FconnectOptions%3D0%26lastChangeId%3D330326078%26lastChangeId64%3D330326078&redirect=1&hid=e8357ffe-403f-41bc-aae2-5d67ba1a7daa&context=eyJodCI6MiwiaGlkIjoiN2U4ZGZmYWUtYTA2Yy00MzI1LWE4MWQtZGE1NmY5ZTg5YjY4IiwicXMiOnt9LCJyciI6IiIsInZoIjoiIiwiY3YiOiIiLCJjcyI6IiJ90#ctx=eyJTaWduSW5Db29raWVEb21haW5zIjpbImh0dHBzOi8vbG9naW4ubWljcm9zb2Z0b25saW5lLmNvbSIsImh0dHBzOi8vbG9naW4ubWljcm9zb2Z0b25saW5lLmNvbSJdfQ2
Request-Context: appId=cid-v1:3142c212-5102-492c-94e2-153eb747f4c0
Access-Control-Expose-Headers: Request-Context
X-Content-Type-Options: nosniff
X-Cache: CONFIG_NOCACHE
X-MSEdge-Ref: Ref A: 4CBF7906543F489AAACD29944BAB4365 Ref B: LON04EDGE0622 Ref C: 2021-10-29T15:05:05Z
Date: Fri, 29 Oct 2021 15:05:05 GMT

[2021-10-29 15:05:05Z INFO RSAFileKeyManager] Loading RSA key parameters from file /azp/.credentials_rsaparams
[2021-10-29 15:05:05Z INFO RSAFileKeyManager] Loading RSA key parameters from file /azp/.credentials_rsaparams
[2021-10-29 15:05:05Z INFO VisualStudioServices] AAD Correlation ID for this token request: Unknown
[2021-10-29 15:05:05Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2021-10-29 15:05:05Z INFO AgentServer] Establish connection with 60 seconds timeout.
[2021-10-29 15:05:05Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2021-10-29 15:05:05Z INFO AgentServer] Establish connection with 60 seconds timeout.
[2021-10-29 15:05:05Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2021-10-29 15:05:05Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2021-10-29 15:05:05Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2021-10-29 15:05:06Z INFO MessageListener] VssConnection created
[2021-10-29 15:05:06Z INFO MessageListener] Session created.
[2021-10-29 15:05:06Z INFO Terminal] WRITE LINE: 2021-10-29 15:05:06Z: Listening for Jobs
[2021-10-29 15:05:06Z INFO JobDispatcher] Set agent/worker IPC timeout to 30 seconds.
[2021-10-29 15:05:07Z INFO RSAFileKeyManager] Loading RSA key parameters from file /azp/.credentials_rsaparams
[2021-10-29 15:05:07Z INFO MessageListener] Message '2' received from session '7929e329-d52f-4cb2-a5c3-6eb6cc6316e3'.
[2021-10-29 15:05:07Z INFO JobDispatcher] Job request 12689 for plan a4292f50-58c8-4f9b-ab8e-ae77178df02d job a2a17486-12d8-5347-a845-7ac6ecb43493 received.
[2021-10-29 15:05:07Z INFO Terminal] WRITE LINE: 2021-10-29 15:05:07Z: Running job: Deploy MapProxy to AWS_Deploy_azure-pipelines-environment-agent-677c6c5d89-bc4mn
[2021-10-29 15:05:07Z INFO AgentServer] Refresh JobRequest VssConnection to get on a different AFD node.
[2021-10-29 15:05:07Z INFO AgentServer] Establish connection with 30 seconds timeout.
[2021-10-29 15:05:07Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2021-10-29 15:05:07Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2021-10-29 15:05:07Z INFO JobDispatcher] Start renew job request 12689 for job a2a17486-12d8-5347-a845-7ac6ecb43493.
[2021-10-29 15:05:07Z INFO JobDispatcher] Successfully renew job request 12689, job is valid till 10/29/2021 15:15:07
[2021-10-29 15:05:07Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:07Z INFO ProcessInvokerWrapper] Starting process:
[2021-10-29 15:05:07Z INFO ProcessInvokerWrapper]   File name: '/azp/bin.2.194.0/Agent.Worker'
[2021-10-29 15:05:07Z INFO ProcessInvokerWrapper]   Arguments: 'spawnclient 118 121'
[2021-10-29 15:05:07Z INFO ProcessInvokerWrapper]   Working directory: '/azp/bin.2.194.0'
[2021-10-29 15:05:07Z INFO ProcessInvokerWrapper]   Require exit code zero: 'False'
[2021-10-29 15:05:07Z INFO ProcessInvokerWrapper]   Encoding web name:  ; code page: ''
[2021-10-29 15:05:07Z INFO ProcessInvokerWrapper]   Force kill process on cancellation: 'True'
[2021-10-29 15:05:07Z INFO ProcessInvokerWrapper]   Redirected STDIN: 'False'
[2021-10-29 15:05:07Z INFO ProcessInvokerWrapper]   Persist current code page: 'False'
[2021-10-29 15:05:07Z INFO ProcessInvokerWrapper]   Keep redirected STDIN open: 'False'
[2021-10-29 15:05:07Z INFO ProcessInvokerWrapper]   High priority process: 'True'
[2021-10-29 15:05:07Z INFO ProcessInvokerWrapper] Process started with process id 375, waiting for process exit.
[2021-10-29 15:05:07Z INFO JobDispatcher] Send job request message to worker for job a2a17486-12d8-5347-a845-7ac6ecb43493 (26 KB).
[2021-10-29 15:05:07Z INFO JobDispatcher] Took 5 ms to send job message to worker
[2021-10-29 15:05:07Z INFO JobNotification] Entering JobStarted Notification
[2021-10-29 15:05:07Z INFO JobNotification] Entering StartMonitor
[2021-10-29 15:05:21Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2021-10-29 15:05:21Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2021-10-29 15:05:21Z INFO ProcessInvokerWrapper] Exited process 375 with exit code 100
[2021-10-29 15:05:21Z INFO ProcessInvokerWrapper] Finished process 375 with exit code 100, and elapsed time 00:00:13.9167870.
[2021-10-29 15:05:21Z INFO JobDispatcher] Worker finished for job a2a17486-12d8-5347-a845-7ac6ecb43493. Code: 100
[2021-10-29 15:05:21Z INFO JobDispatcher] finish job request for job a2a17486-12d8-5347-a845-7ac6ecb43493 with result: Succeeded
[2021-10-29 15:05:21Z INFO Terminal] WRITE LINE: 2021-10-29 15:05:21Z: Job Deploy MapProxy to AWS_Deploy_azure-pipelines-environment-agent-677c6c5d89-bc4mn completed with result: Succeeded
[2021-10-29 15:05:21Z INFO JobDispatcher] Stop renew job request for job a2a17486-12d8-5347-a845-7ac6ecb43493.
[2021-10-29 15:05:21Z INFO JobDispatcher] job renew has been canceled, stop renew job request 12689.
[2021-10-29 15:05:21Z INFO JobNotification] Entering JobCompleted Notification
[2021-10-29 15:05:21Z INFO JobNotification] Entering EndMonitor
[2021-10-29 15:05:33Z INFO AgentProcess] Agent package linux-x64.
[2021-10-29 15:05:33Z INFO AgentProcess] Running on Linux (X64).
[2021-10-29 15:05:33Z INFO AgentProcess] RuntimeInformation: Linux 5.4.149-73.259.amzn2.x86_64 #1 SMP Mon Sep 27 12:48:12 UTC 2021.
[2021-10-29 15:05:33Z INFO AgentProcess] Version: 2.194.0
[2021-10-29 15:05:33Z INFO AgentProcess] Commit: 7dbde4ca1590dc331acd879fb240c5428268b30d
[2021-10-29 15:05:33Z INFO AgentProcess] Culture: 
[2021-10-29 15:05:33Z INFO AgentProcess] UI Culture: 
[2021-10-29 15:05:33Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:33Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:33Z INFO AgentProcess] Validating directory permissions for: '/azp'
[2021-10-29 15:05:33Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:33Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:33Z INFO CommandSettings] Remove {
  "Auth": "PAT",
  "LaunchBrowser": false,
  "Password": null,
  "Token": "***",
  "Unattended": true,
  "UserName": null,
  "Help": false,
  "Version": false
}
[2021-10-29 15:05:33Z INFO AgentProcess] Arguments parsed
[2021-10-29 15:05:33Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:33Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:33Z INFO HostContext] Well known config file 'Proxy': '/azp/.proxy'
[2021-10-29 15:05:33Z INFO VstsAgentWebProxy] No proxy setting found.
[2021-10-29 15:05:33Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:33Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:33Z INFO HostContext] Well known config file 'Certificates': '/azp/.certificates'
[2021-10-29 15:05:33Z INFO AgentCertificateManager] No certificate setting found.
[2021-10-29 15:05:33Z INFO Agent] ExecuteCommand
[2021-10-29 15:05:33Z INFO ConfigurationStore] currentAssemblyLocation: /azp/bin.2.194.0/Agent.Listener.dll
[2021-10-29 15:05:33Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:33Z INFO ConfigurationStore] binPath: /azp/bin.2.194.0
[2021-10-29 15:05:33Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:33Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:33Z INFO ConfigurationStore] RootFolder: /azp
[2021-10-29 15:05:33Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:33Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:33Z INFO HostContext] Well known config file 'Agent': '/azp/.agent'
[2021-10-29 15:05:33Z INFO ConfigurationStore] ConfigFilePath: /azp/.agent
[2021-10-29 15:05:33Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:33Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:33Z INFO HostContext] Well known config file 'Credentials': '/azp/.credentials'
[2021-10-29 15:05:33Z INFO ConfigurationStore] CredFilePath: /azp/.credentials
[2021-10-29 15:05:33Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:33Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:33Z INFO HostContext] Well known config file 'Service': '/azp/.service'
[2021-10-29 15:05:33Z INFO ConfigurationStore] ServiceConfigFilePath: /azp/.service
[2021-10-29 15:05:33Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:33Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:33Z INFO HostContext] Well known config file 'Autologon': '/azp/.autologon'
[2021-10-29 15:05:33Z INFO ConfigurationStore] AutoLogonSettingsFilePath: /azp/.autologon
[2021-10-29 15:05:33Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:33Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:33Z INFO HostContext] Well known config file 'Options': '/azp/.options'
[2021-10-29 15:05:33Z INFO ConfigurationStore] RuntimeOptionsFilePath: /azp/.options
[2021-10-29 15:05:33Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:33Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:33Z INFO HostContext] Well known config file 'SetupInfo': '/azp/.setup_info'
[2021-10-29 15:05:33Z INFO ConfigurationStore] SetupInfoFilePath: /azp/.setup_info
[2021-10-29 15:05:33Z INFO ConfigurationStore] IsServiceConfigured()
[2021-10-29 15:05:33Z INFO ConfigurationStore] IsServiceConfigured: False
[2021-10-29 15:05:33Z INFO Terminal] WRITE LINE: Removing agent from the server
[2021-10-29 15:05:33Z INFO ConfigurationStore] IsConfigured()
[2021-10-29 15:05:33Z INFO ConfigurationStore] IsConfigured: True
[2021-10-29 15:05:33Z INFO ConfigurationStore] HasCredentials()
[2021-10-29 15:05:33Z INFO ConfigurationStore] stored True
[2021-10-29 15:05:33Z INFO ConfigurationStore] Read setting file: 320 chars
[2021-10-29 15:05:33Z INFO ConfigurationManager] GetCredentialProvider
[2021-10-29 15:05:33Z INFO CommandSettings] Arg 'auth': 'PAT'
[2021-10-29 15:05:33Z INFO ConfigurationManager] Creating credential for auth: PAT
[2021-10-29 15:05:33Z INFO CredentialManager] GetCredentialProvider
[2021-10-29 15:05:33Z INFO CredentialManager] Creating type PAT
[2021-10-29 15:05:33Z INFO CredentialManager] Creating credential type: PAT
[2021-10-29 15:05:33Z INFO PersonalAccessToken] EnsureCredential
[2021-10-29 15:05:33Z INFO CommandSettings] Arg 'token': '***'
[2021-10-29 15:05:33Z INFO PersonalAccessToken] GetVssCredentials
[2021-10-29 15:05:33Z INFO PersonalAccessToken] token retrieved: 52 chars
[2021-10-29 15:05:33Z INFO PersonalAccessToken] cred created
[2021-10-29 15:05:33Z INFO ConfigurationManager] cred retrieved
[2021-10-29 15:05:33Z INFO ConfigurationManager] Agent configured for deploymentGroup : False
[2021-10-29 15:05:33Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Listener.Configuration.IConfigurationProvider'
[2021-10-29 15:05:33Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.BuildReleasesAgentConfigProvider, Agent.Listener
[2021-10-29 15:05:33Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.DeploymentGroupAgentConfigProvider, Agent.Listener
[2021-10-29 15:05:33Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.SharedDeploymentAgentConfigProvider, Agent.Listener
[2021-10-29 15:05:33Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.EnvironmentVMResourceConfigProvider, Agent.Listener
[2021-10-29 15:05:33Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2021-10-29 15:05:33Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2021-10-29 15:05:33Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2021-10-29 15:05:33Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2021-10-29 15:05:33Z INFO Terminal] WRITE LINE: Connecting to server ...
[2021-10-29 15:05:33Z INFO EnvironmentVMResourceConfigProvider] Test connection with environment
[2021-10-29 15:05:33Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2021-10-29 15:05:34Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2021-10-29 15:05:34Z INFO EnvironmentVMResourceConfigProvider] Connection complete for environment
[2021-10-29 15:05:34Z INFO EnvironmentVMResourceConfigProvider] Deleting environment virtual machine resource with id: '25'
[2021-10-29 15:05:34Z INFO EnvironmentVMResourceConfigProvider] Environment virtual machine resource with id: '25' has been successfully deleted.
[2021-10-29 15:05:34Z INFO Terminal] WRITE LINE: Succeeded: Removing agent from the server
[2021-10-29 15:05:34Z INFO Terminal] WRITE LINE: Removing .credentials
[2021-10-29 15:05:34Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:34Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:34Z INFO HostContext] Well known config file 'RSACredentials': '/azp/.credentials_rsaparams'
[2021-10-29 15:05:34Z INFO RSAFileKeyManager] Deleting RSA key parameters file /azp/.credentials_rsaparams
[2021-10-29 15:05:34Z INFO Terminal] WRITE LINE: Succeeded: Removing .credentials
[2021-10-29 15:05:34Z INFO Terminal] WRITE LINE: Removing .agent
[2021-10-29 15:05:34Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:34Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:34Z INFO HostContext] Well known config file 'ProxyCredentials': '/azp/.proxycredentials'
[2021-10-29 15:05:34Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:34Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:34Z INFO HostContext] Well known config file 'ProxyBypass': '/azp/.proxybypass'
[2021-10-29 15:05:34Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:34Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:34Z INFO HostContext] Well known config file 'Proxy': '/azp/.proxy'
[2021-10-29 15:05:34Z INFO VstsAgentWebProxy] Delete .proxy file: /azp/.proxy
[2021-10-29 15:05:34Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:34Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:34Z INFO HostContext] Well known config file 'Certificates': '/azp/.certificates'
[2021-10-29 15:05:34Z INFO Terminal] WRITE LINE: Succeeded: Removing .agent
[2021-10-29 15:05:07Z INFO Program] Version: 2.194.0
[2021-10-29 15:05:07Z INFO Program] Commit: 7dbde4ca1590dc331acd879fb240c5428268b30d
[2021-10-29 15:05:07Z INFO Program] Culture: 
[2021-10-29 15:05:07Z INFO Program] UI Culture: 
[2021-10-29 15:05:07Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:07Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:07Z INFO HostContext] Well known config file 'Proxy': '/azp/.proxy'
[2021-10-29 15:05:07Z INFO VstsAgentWebProxy] No proxy setting found.
[2021-10-29 15:05:07Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:07Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:07Z INFO HostContext] Well known config file 'Certificates': '/azp/.certificates'
[2021-10-29 15:05:07Z INFO AgentCertificateManager] No certificate setting found.
[2021-10-29 15:05:07Z INFO Worker] Waiting to receive the job message from the channel.
[2021-10-29 15:05:07Z INFO Worker] Message received.
[2021-10-29 15:05:08Z INFO Worker] Job message:
 {
  "mask": [
    {
      "type": "regex",
      "value": "***"
    },
    {
      "type": "regex",
      "value": "***"
    }
  ],
  "steps": [
    {
      "inputs": {
        "alias": "current",
        "mode": "automatic",
        "artifact": "KubernetesResourceManifests",
        "artifactName": "KubernetesResourceManifests",
        "itemPattern": "**",
        "downloadPath": "$(Pipeline.Workspace)/"
      },
      "type": "task",
      "reference": {
        "id": "a433f589-fce1-4460-9ee6-44a624aeb1fb",
        "name": "DownloadBuildArtifacts",
        "version": "0.190.0"
      },
      "id": "29b888a0-a144-5691-0c07-7497e1d5a653",
      "name": "Download_KubernetesResourceManifests0",
      "displayName": "Download Artifact"
    },
    {
      "inputs": {
        "connectionType": "None",
        "command": "apply",
        "arguments": "-f $(Agent.BuildDirectory)/$(ArtifactName)/mapproxy.yaml",
        "secretType": "generic",
        "secretArguments": "--from-literal=DatabaseConnection__Password=\"$(db_password)\"",
        "secretName": "map-proxy-secret-env"
      },
      "type": "task",
      "reference": {
        "id": "cbc316a2-586f-4def-be79-488a1f503564",
        "name": "Kubernetes",
        "version": "1.181.0"
      },
      "id": "41e14dad-eb8a-5f61-7fca-186da6f273f6",
      "name": "Kubernetes",
      "displayName": "Deploy MapProxy"
    }
  ],
  "variables": {
    "system.debug": {
      "value": "true",
      "isReadOnly": true
    },
    "agent.diagnostic": {
      "value": "true",
      "isReadOnly": true
    },
    "Environment": {
      "value": "Development"
    },
    "ArtifactName": {
      "value": "KubernetesResourceManifests"
    },
    "resources.triggeringCategory": {
      "value": ""
    },
    "resources.triggeringAlias": {
      "value": ""
    },
    "db_admin_user": {
      "value": "review_website_admin"
    },
    "db_user": {
      "value": "review_website_app"
    },
    "db_password": {
      "value": "***",
      "isSecret": true
    },
    "db_admin_password": {
      "value": "***",
      "isSecret": true
    },
    "system": {
      "value": "build",
      "isReadOnly": true
    },
    "system.hosttype": {
      "value": "build",
      "isReadOnly": true
    },
    "system.servertype": {
      "value": "Hosted",
      "isReadOnly": true
    },
    "system.culture": {
      "value": "en-US",
      "isReadOnly": true
    },
    "system.collectionId": {
      "value": "e8357ffe-403f-41bc-aae2-5d67ba1a7daa",
      "isReadOnly": true
    },
    "system.collectionUri": {
      "value": "https://dev.azure.com/jbaconsulting/",
      "isReadOnly": true
    },
    "system.teamFoundationCollectionUri": {
      "value": "https://dev.azure.com/jbaconsulting/",
      "isReadOnly": true
    },
    "system.taskDefinitionsUri": {
      "value": "https://dev.azure.com/jbaconsulting/",
      "isReadOnly": true
    },
    "system.pipelineStartTime": {
      "value": "2021-10-29 16:04:57+01:00",
      "isReadOnly": true
    },
    "system.teamProject": {
      "value": "NaFRA2",
      "isReadOnly": true
    },
    "system.teamProjectId": {
      "value": "9f91a63f-06b8-4e02-987b-e6b84d64dd8e",
      "isReadOnly": true
    },
    "system.definitionId": {
      "value": "83",
      "isReadOnly": true
    },
    "build.definitionName": {
      "value": "Review Website MapProxy",
      "isReadOnly": true
    },
    "build.definitionVersion": {
      "value": "2",
      "isReadOnly": true
    },
    "build.queuedBy": {
      "value": "[PII]",
      "isReadOnly": true
    },
    "build.queuedById": {
      "value": "1703edc9-e8c8-47a4-bbd7-aed5852c0bb7",
      "isReadOnly": true
    },
    "build.requestedFor": {
      "value": "[PII]",
      "isReadOnly": true
    },
    "build.requestedForId": {
      "value": "1703edc9-e8c8-47a4-bbd7-aed5852c0bb7",
      "isReadOnly": true
    },
    "build.requestedForEmail": {
      "value": "[PII]",
      "isReadOnly": true
    },
    "build.sourceVersion": {
      "value": "[PII]",
      "isReadOnly": true
    },
    "build.sourceBranch": {
      "value": "[PII]",
      "isReadOnly": true
    },
    "build.sourceBranchName": {
      "value": "[PII]",
      "isReadOnly": true
    },
    "build.reason": {
      "value": "Manual",
      "isReadOnly": true
    },
    "system.pullRequest.isFork": {
      "value": "False",
      "isReadOnly": true
    },
    "system.jobParallelismTag": {
      "value": "Private",
      "isReadOnly": true
    },
    "system.enableAccessToken": {
      "value": "SecretVariable",
      "isReadOnly": true
    },
    "MSDEPLOY_HTTP_USER_AGENT": {
      "value": "VSTS_e8357ffe-403f-41bc-aae2-5d67ba1a7daa_build_83_0",
      "isReadOnly": true
    },
    "AZURE_HTTP_USER_AGENT": {
      "value": "VSTS_e8357ffe-403f-41bc-aae2-5d67ba1a7daa_build_83_0",
      "isReadOnly": true
    },
    "build.buildId": {
      "value": "8275",
      "isReadOnly": true
    },
    "build.buildUri": {
      "value": "vstfs:///Build/Build/8275",
      "isReadOnly": true
    },
    "build.buildNumber": {
      "value": "20211029.4",
      "isReadOnly": true
    },
    "build.containerId": {
      "value": "12387909",
      "isReadOnly": true
    },
    "system.isScheduled": {
      "value": "False",
      "isReadOnly": true
    },
    "system.definitionName": {
      "value": "Review Website MapProxy",
      "isReadOnly": true
    },
    "system.planId": {
      "value": "a4292f50-58c8-4f9b-ab8e-ae77178df02d",
      "isReadOnly": true
    },
    "system.timelineId": {
      "value": "a4292f50-58c8-4f9b-ab8e-ae77178df02d",
      "isReadOnly": true
    },
    "system.stageDisplayName": {
      "value": "Deploy",
      "isReadOnly": true
    },
    "system.stageId": {
      "value": "d4a9a205-d52e-57fb-7b17-15a9d984af62",
      "isReadOnly": true
    },
    "system.stageName": {
      "value": "Deploy",
      "isReadOnly": true
    },
    "system.stageAttempt": {
      "value": "1",
      "isReadOnly": true
    },
    "system.phaseDisplayName": {
      "value": "Deploy MapProxy to AWS",
      "isReadOnly": true
    },
    "system.phaseId": {
      "value": "7aafabc8-93d7-51d2-cb31-d761bafc8700",
      "isReadOnly": true
    },
    "system.phaseName": {
      "value": "DeployMapProxy",
      "isReadOnly": true
    },
    "system.phaseAttempt": {
      "value": "1",
      "isReadOnly": true
    },
    "Strategy.CycleName": {
      "value": "azure-pipelines-environment-agent-677c6c5d89-bc4mn"
    },
    "Strategy.Name": {
      "value": "runOnce"
    },
    "Environment.ResourceId": {
      "value": "25"
    },
    "Environment.ResourceName": {
      "value": "azure-pipelines-environment-agent-677c6c5d89-bc4mn"
    },
    "Environment.Id": {
      "value": "2"
    },
    "Environment.Name": {
      "value": "NaFRA2 - Review Website"
    },
    "Environment.DeploymentPhaseIdentifier": {
      "value": "a4292f50-58c8-4f9b-ab8e-ae77178df02d.deploy.deploymapproxy"
    },
    "system.jobIdentifier": {
      "value": "Deploy.DeployMapProxy.Deploy_azure-pipelines-environment-agent-677c6c5d89-bc4mn",
      "isReadOnly": true
    },
    "system.jobAttempt": {
      "value": "1",
      "isReadOnly": true
    },
    "system.jobDisplayName": {
      "value": "Deploy MapProxy to AWS_Deploy_azure-pipelines-environment-agent-677c6c5d89-bc4mn",
      "isReadOnly": true
    },
    "system.jobId": {
      "value": "a2a17486-12d8-5347-a845-7ac6ecb43493",
      "isReadOnly": true
    },
    "system.jobName": {
      "value": "Deploy_azure-pipelines-environment-agent-677c6c5d89-bc4mn",
      "isReadOnly": true
    },
    "system.jobTimeout": {
      "value": "60",
      "isReadOnly": true
    },
    "system.accessToken": {
      "value": ***,
      "isSecret": true
    },
    "agent.retainDefaultEncoding": {
      "value": "false",
      "isReadOnly": true
    },
    "agent.LogToBlobstorageService": {
      "value": "true",
      "isReadOnly": true
    },
    "agent.readOnlyVariables": {
      "value": "true",
      "isReadOnly": true
    },
    "agent.useWorkspaceId": {
      "value": "true",
      "isReadOnly": true
    },
    "system.postLinesSpeed": {
      "value": "500",
      "isReadOnly": true
    },
    "agent.taskRestrictionsEnforcementMode": {
      "value": "Enabled",
      "isReadOnly": true
    },
    "agent.disablelogplugin.TestResultLogPlugin": {
      "value": "true",
      "isReadOnly": true
    },
    "agent.disablelogplugin.TestFilePublisherPlugin": {
      "value": "true",
      "isReadOnly": true
    },
    "build.repository.id": {
      "value": "7c6f69ec-48bc-4c67-8e66-410409987544",
      "isReadOnly": true
    },
    "build.repository.name": {
      "value": "Review Website",
      "isReadOnly": true
    },
    "build.repository.uri": {
      "value": "https://jbaconsulting@dev.azure.com/jbaconsulting/NaFRA2/_git/Review%20Website",
      "isReadOnly": true
    },
    "build.sourceVersionAuthor": {
      "value": "[PII]",
      "isReadOnly": true
    },
    "build.sourceVersionMessage": {
      "value": "Merged PR 3340: Updates environment switch for MapProxy.\n\nUpdates environment switch for MapProxy.",
      "isReadOnly": true
    }
  },
  "messageType": "PipelineAgentJobRequest",
  "plan": {
    "scopeIdentifier": "9f91a63f-06b8-4e02-987b-e6b84d64dd8e",
    "planType": "Build",
    "version": 18,
    "planId": "a4292f50-58c8-4f9b-ab8e-ae77178df02d",
    "planGroup": "Build:9f91a63f-06b8-4e02-987b-e6b84d64dd8e:8275",
    "artifactUri": "vstfs:///Build/Build/8275",
    "artifactLocation": null,
    "definition": {
      "_links": {
        "web": {
          "href": "https://dev.azure.com/jbaconsulting/9f91a63f-06b8-4e02-987b-e6b84d64dd8e/_build/definition?definitionId=83"
        },
        "self": {
          "href": "https://dev.azure.com/jbaconsulting/9f91a63f-06b8-4e02-987b-e6b84d64dd8e/_apis/build/Definitions/83"
        }
      },
      "id": 83,
      "name": "Review Website MapProxy"
    },
    "owner": {
      "_links": {
        "web": {
          "href": "https://dev.azure.com/jbaconsulting/9f91a63f-06b8-4e02-987b-e6b84d64dd8e/_build/results?buildId=8275"
        },
        "self": {
          "href": "https://dev.azure.com/jbaconsulting/9f91a63f-06b8-4e02-987b-e6b84d64dd8e/_apis/build/Builds/8275"
        }
      },
      "id": 8275,
      "name": "20211029.4"
    }
  },
  "timeline": {
    "id": "a4292f50-58c8-4f9b-ab8e-ae77178df02d",
    "changeId": 36,
    "location": null
  },
  "jobId": "a2a17486-12d8-5347-a845-7ac6ecb43493",
  "jobDisplayName": "Deploy MapProxy to AWS_Deploy_azure-pipelines-environment-agent-677c6c5d89-bc4mn",
  "jobName": "Deploy_azure-pipelines-environment-agent-677c6c5d89-bc4mn",
  "jobContainer": null,
  "requestId": 0,
  "lockedUntil": "0001-01-01T00:00:00",
  "resources": {
    "endpoints": [
      {
        "data": {
          "ServerId": "e8357ffe-403f-41bc-aae2-5d67ba1a7daa",
          "ServerName": "jbaconsulting"
        },
        "name": "SystemVssConnection",
        "url": "https://dev.azure.com/jbaconsulting/",
        "authorization": {
          "parameters": {
            "AccessToken": ***
          },
          "scheme": "OAuth"
        },
        "isShared": false,
        "isReady": true
      }
    ],
    "repositories": [
      {
        "properties": {
          "id": "7c6f69ec-48bc-4c67-8e66-410409987544",
          "type": "Git",
          "version": "90ea224482df6c9756e74a2b24d2a6776440039c",
          "name": "Review Website",
          "project": "9f91a63f-06b8-4e02-987b-e6b84d64dd8e",
          "defaultBranch": "refs/heads/develop",
          "ref": "refs/heads/develop",
          "url": "https://jbaconsulting@dev.azure.com/jbaconsulting/NaFRA2/_git/Review%20Website",
          "versionInfo": {
            "author": "[PII]"
          },
          "checkoutOptions": {}
        },
        "alias": "self",
        "endpoint": {
          "name": "SystemVssConnection"
        }
      }
    ]
  },
  "workspace": {
    "clean": "all"
  }
}
[2021-10-29 15:05:08Z INFO JobRunner] Job ID a2a17486-12d8-5347-a845-7ac6ecb43493
[2021-10-29 15:05:08Z INFO JobRunner] Creating job server with URL: https://dev.azure.com/jbaconsulting/
[2021-10-29 15:05:08Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2021-10-29 15:05:08Z INFO Worker] Listening for cancel message from the channel.
[2021-10-29 15:05:08Z INFO Worker] Waiting for the job to complete or for a cancel message from the channel.
[2021-10-29 15:05:08Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2021-10-29 15:05:08Z INFO JobServerQueue] Start process web console line queue.
[2021-10-29 15:05:08Z INFO JobServerQueue] Start process file upload queue.
[2021-10-29 15:05:08Z INFO JobServerQueue] Start process timeline update queue.
[2021-10-29 15:05:08Z INFO ConfigurationStore] currentAssemblyLocation: /azp/bin.2.194.0/Agent.Worker.dll
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:08Z INFO ConfigurationStore] binPath: /azp/bin.2.194.0
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:08Z INFO ConfigurationStore] RootFolder: /azp
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:08Z INFO HostContext] Well known config file 'Agent': '/azp/.agent'
[2021-10-29 15:05:08Z INFO ConfigurationStore] ConfigFilePath: /azp/.agent
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:08Z INFO HostContext] Well known config file 'Credentials': '/azp/.credentials'
[2021-10-29 15:05:08Z INFO ConfigurationStore] CredFilePath: /azp/.credentials
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:08Z INFO HostContext] Well known config file 'Service': '/azp/.service'
[2021-10-29 15:05:08Z INFO ConfigurationStore] ServiceConfigFilePath: /azp/.service
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:08Z INFO HostContext] Well known config file 'Autologon': '/azp/.autologon'
[2021-10-29 15:05:08Z INFO ConfigurationStore] AutoLogonSettingsFilePath: /azp/.autologon
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:08Z INFO HostContext] Well known config file 'Options': '/azp/.options'
[2021-10-29 15:05:08Z INFO ConfigurationStore] RuntimeOptionsFilePath: /azp/.options
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:08Z INFO HostContext] Well known config file 'SetupInfo': '/azp/.setup_info'
[2021-10-29 15:05:08Z INFO ConfigurationStore] SetupInfoFilePath: /azp/.setup_info
[2021-10-29 15:05:08Z INFO ConfigurationStore] Read setting file: 320 chars
[2021-10-29 15:05:08Z INFO ExecutionContext] WorkspaceIdentifier 'cb0406f2edc8029d8d203713d7e26f17cce65c0d' created for repos Microsoft.VisualStudio.Services.Agent.Worker.Build.RepositoryTrackingInfo
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Diag': '/azp/_diag'
[2021-10-29 15:05:08Z INFO JobRunner] Starting the job execution context.
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Work': '/azp/_work'
[2021-10-29 15:05:08Z INFO JobRunner] Validating directory permissions for: '/azp/_work'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Work': '/azp/_work'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Work': '/azp/_work'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Work': '/azp/_work'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Work': '/azp/_work'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Tools': '/azp/_work/_tool'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Work': '/azp/_work'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Temp': '/azp/_work/_temp'
[2021-10-29 15:05:08Z INFO JobRunner] Creating task server with https://dev.azure.com/jbaconsulting/
[2021-10-29 15:05:08Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2021-10-29 15:05:08Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2021-10-29 15:05:08Z INFO JobRunner] Getting job extension.
[2021-10-29 15:05:08Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Worker.IJobExtension'
[2021-10-29 15:05:08Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildJobExtension, Agent.Worker
[2021-10-29 15:05:08Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Release.ReleaseJobExtension, Agent.Worker
[2021-10-29 15:05:08Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Release.DeploymentJobExtension, Agent.Worker
[2021-10-29 15:05:08Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Maintenance.MaintenanceJobExtension, Agent.Worker
[2021-10-29 15:05:08Z INFO JobRunner] Initialize job. Getting all job steps.
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Diag': '/azp/_diag'
[2021-10-29 15:05:08Z INFO BuildJobExtension] Run initial step from extension BuildJobExtension.
[2021-10-29 15:05:08Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Worker.Build.ISourceProvider'
[2021-10-29 15:05:08Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Build.ExternalGitSourceProvider, Agent.Worker
[2021-10-29 15:05:08Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Build.GitHubSourceProvider, Agent.Worker
[2021-10-29 15:05:08Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Build.GitHubEnterpriseSourceProvider, Agent.Worker
[2021-10-29 15:05:08Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Build.BitbucketSourceProvider, Agent.Worker
[2021-10-29 15:05:08Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Build.SvnSourceProvider, Agent.Worker
[2021-10-29 15:05:08Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Build.TfsGitSourceProvider, Agent.Worker
[2021-10-29 15:05:08Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Build.TfsVCSourceProvider, Agent.Worker
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Work': '/azp/_work'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Work': '/azp/_work'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Work': '/azp/_work'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Work': '/azp/_work'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Work': '/azp/_work'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Work': '/azp/_work'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Work': '/azp/_work'
[2021-10-29 15:05:08Z INFO BuildDirectoryManager] Checking if build directory exists: '/azp/_work/1'
[2021-10-29 15:05:08Z INFO BuildDirectoryManager] Creating build directory.
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Work': '/azp/_work'
[2021-10-29 15:05:08Z INFO BuildDirectoryManager] Checking if artifacts directory exists: '/azp/_work/1/a'
[2021-10-29 15:05:08Z INFO BuildDirectoryManager] Creating artifacts directory.
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Work': '/azp/_work'
[2021-10-29 15:05:08Z INFO BuildDirectoryManager] Checking if test results directory exists: '/azp/_work/1/TestResults'
[2021-10-29 15:05:08Z INFO BuildDirectoryManager] Creating test results directory.
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Work': '/azp/_work'
[2021-10-29 15:05:08Z INFO BuildDirectoryManager] Creating binaries directory.
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Work': '/azp/_work'
[2021-10-29 15:05:08Z INFO BuildDirectoryManager] Creating source directory.
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Work': '/azp/_work'
[2021-10-29 15:05:08Z INFO BuildDirectoryManager] Set repository path for repository self to '/azp/_work/1/s'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Work': '/azp/_work'
[2021-10-29 15:05:08Z INFO BuildJobExtension] Downloading task definitions.
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Work': '/azp/_work'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Tasks': '/azp/_work/_tasks'
[2021-10-29 15:05:08Z INFO TaskManager] Ensuring task exists: ID 'a433f589-fce1-4460-9ee6-44a624aeb1fb', version '0.190.0', name 'DownloadBuildArtifacts', directory '/azp/_work/_tasks/DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb/0.190.0'.
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Work': '/azp/_work'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'TaskZips': '/azp/_work/_taskzips'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Work': '/azp/_work'
[2021-10-29 15:05:08Z INFO HostContext] Well known directory 'Tasks': '/azp/_work/_tasks'
[2021-10-29 15:05:09Z INFO JobServerQueue] Try to append 1 batches web console lines for record 'a2a17486-12d8-5347-a845-7ac6ecb43493', success rate: 1/1.
[2021-10-29 15:05:09Z INFO JobServerQueue] Try to append 1 batches web console lines for record 'a2a17486-12d8-5347-a845-7ac6ecb43493', success rate: 1/1.
[2021-10-29 15:05:09Z INFO JobServerQueue] Try to append 1 batches web console lines for record '981b51a9-b3d4-4b18-984c-6b992704d5ee', success rate: 1/1.
[2021-10-29 15:05:11Z INFO TaskManager] Finished getting task.
[2021-10-29 15:05:11Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:11Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:11Z INFO HostContext] Well known directory 'Work': '/azp/_work'
[2021-10-29 15:05:11Z INFO HostContext] Well known directory 'Tasks': '/azp/_work/_tasks'
[2021-10-29 15:05:11Z INFO TaskManager] Ensuring task exists: ID 'cbc316a2-586f-4def-be79-488a1f503564', version '1.181.0', name 'Kubernetes', directory '/azp/_work/_tasks/Kubernetes_cbc316a2-586f-4def-be79-488a1f503564/1.181.0'.
[2021-10-29 15:05:11Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:11Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:11Z INFO HostContext] Well known directory 'Work': '/azp/_work'
[2021-10-29 15:05:11Z INFO HostContext] Well known directory 'TaskZips': '/azp/_work/_taskzips'
[2021-10-29 15:05:11Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:11Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:11Z INFO HostContext] Well known directory 'Work': '/azp/_work'
[2021-10-29 15:05:11Z INFO HostContext] Well known directory 'Tasks': '/azp/_work/_tasks'
[2021-10-29 15:05:11Z INFO JobServerQueue] Try to append 1 batches web console lines for record '981b51a9-b3d4-4b18-984c-6b992704d5ee', success rate: 1/1.
[2021-10-29 15:05:12Z INFO TaskManager] Finished getting task.
[2021-10-29 15:05:12Z INFO BuildJobExtension] Parsing all task's condition inputs.
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'Work': '/azp/_work'
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'Tasks': '/azp/_work/_tasks'
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'Work': '/azp/_work'
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'TaskZips': '/azp/_work/_taskzips'
[2021-10-29 15:05:12Z INFO TaskManager] Loading task definition '/azp/_work/_tasks/DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb/0.190.0/task.json'.
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'Work': '/azp/_work'
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'Tasks': '/azp/_work/_tasks'
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'Work': '/azp/_work'
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'TaskZips': '/azp/_work/_taskzips'
[2021-10-29 15:05:12Z INFO TaskManager] Loading task definition '/azp/_work/_tasks/Kubernetes_cbc316a2-586f-4def-be79-488a1f503564/1.181.0/task.json'.
[2021-10-29 15:05:12Z INFO BuildJobExtension] Adding pre-job step from extension.
[2021-10-29 15:05:12Z INFO BuildJobExtension] Adding post-job step from extension.
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'Diag': '/azp/_diag'
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'Diag': '/azp/_diag'
[2021-10-29 15:05:12Z INFO BuildJobExtension] Adding post-job steps from tasks.
[2021-10-29 15:05:12Z INFO BuildJobExtension] Total accessible running process: 6.
[2021-10-29 15:05:12Z INFO JobRunner] Total job steps: 2.
[2021-10-29 15:05:12Z INFO JobRunner] Run all job steps.
[2021-10-29 15:05:12Z INFO StepsRunner] Processing step: DisplayName='Download Artifact', ContinueOnError=False, Enabled=True
[2021-10-29 15:05:12Z INFO ExpressionManager] Evaluating: SucceededNode()
[2021-10-29 15:05:12Z INFO ExpressionManager] Result: True
[2021-10-29 15:05:12Z INFO StepsRunner] Starting the step.
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'Work': '/azp/_work'
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'Tasks': '/azp/_work/_tasks'
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'Work': '/azp/_work'
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'TaskZips': '/azp/_work/_taskzips'
[2021-10-29 15:05:12Z INFO TaskManager] Loading task definition '/azp/_work/_tasks/DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb/0.190.0/task.json'.
[2021-10-29 15:05:12Z INFO TaskRunner] Get handler data for target platform Linux
[2021-10-29 15:05:12Z INFO TaskRunner] Handler data is of type Microsoft.VisualStudio.Services.Agent.Worker.Node10HandlerData
[2021-10-29 15:05:12Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Worker.IWorkerCommandExtension'
[2021-10-29 15:05:12Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.TaskCommandExtension, Agent.Worker
[2021-10-29 15:05:12Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Build.ArtifactCommandExtension, Agent.Worker
[2021-10-29 15:05:12Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildCommandExtension, Agent.Worker
[2021-10-29 15:05:12Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.CodeCoverage.CodeCoverageCommandExtension, Agent.Worker
[2021-10-29 15:05:12Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.TestResults.ResultsCommandExtension, Agent.Worker
[2021-10-29 15:05:12Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Telemetry.TelemetryCommandExtension, Agent.Worker
[2021-10-29 15:05:12Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Release.ReleaseCommandExtension, Agent.Worker
[2021-10-29 15:05:12Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.PluginInternalCommandExtension, Agent.Worker
[2021-10-29 15:05:12Z INFO WorkerCommandManager] Register command extension for area task
[2021-10-29 15:05:12Z INFO WorkerCommandManager] Register command extension for area artifact
[2021-10-29 15:05:12Z INFO WorkerCommandManager] Register command extension for area build
[2021-10-29 15:05:12Z INFO WorkerCommandManager] Register command extension for area codecoverage
[2021-10-29 15:05:12Z INFO WorkerCommandManager] Register command extension for area results
[2021-10-29 15:05:12Z INFO WorkerCommandManager] Register command extension for area telemetry
[2021-10-29 15:05:12Z INFO WorkerCommandManager] Register command extension for area release
[2021-10-29 15:05:12Z INFO WorkerCommandManager] Register command extension for area plugininternal
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'Work': '/azp/_work'
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'Externals': '/azp/externals'
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'Work': '/azp/_work'
[2021-10-29 15:05:12Z INFO NodeHandler] Inspect node_modules folder, make sure vsts-task-lib doesn't overwrite String.startsWith/endsWith.
[2021-10-29 15:05:12Z INFO NodeHandler] Scan node_modules folder, looking for vsts-task-lib\extensions.js
[2021-10-29 15:05:12Z INFO NodeHandler] Finished scan and correct extensions.js under vsts-task-lib
[2021-10-29 15:05:12Z INFO NodeHandler] Task.json has node10 handler data: True, use node10 for node tasks: False
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:12Z INFO HostContext] Well known directory 'Externals': '/azp/externals'
[2021-10-29 15:05:12Z INFO ProcessInvokerWrapper] Starting process:
[2021-10-29 15:05:12Z INFO ProcessInvokerWrapper]   File name: '/azp/externals/node10/bin/node'
[2021-10-29 15:05:12Z INFO ProcessInvokerWrapper]   Arguments: '"/azp/_work/_tasks/DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb/0.190.0/main.js"'
[2021-10-29 15:05:12Z INFO ProcessInvokerWrapper]   Working directory: '/azp/_work/1/s'
[2021-10-29 15:05:12Z INFO ProcessInvokerWrapper]   Require exit code zero: 'True'
[2021-10-29 15:05:12Z INFO ProcessInvokerWrapper]   Encoding web name:  ; code page: ''
[2021-10-29 15:05:12Z INFO ProcessInvokerWrapper]   Force kill process on cancellation: 'False'
[2021-10-29 15:05:12Z INFO ProcessInvokerWrapper]   Redirected STDIN: 'False'
[2021-10-29 15:05:12Z INFO ProcessInvokerWrapper]   Persist current code page: 'False'
[2021-10-29 15:05:12Z INFO ProcessInvokerWrapper]   Keep redirected STDIN open: 'False'
[2021-10-29 15:05:12Z INFO ProcessInvokerWrapper]   High priority process: 'False'
[2021-10-29 15:05:12Z INFO ProcessInvokerWrapper] Failed to update oom_score_adj for PID: 396.
[2021-10-29 15:05:12Z INFO ProcessInvokerWrapper] System.UnauthorizedAccessException: Access to the path '/proc/396/oom_score_adj' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.FlushWriteBuffer()
   at System.IO.FileStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.StreamWriter.CloseStreamFromDispose(Boolean disposing)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at System.IO.File.WriteAllText(String path, String contents)
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.WriteProcessOomScoreAdj(Int32 processId, Int32 oomScoreAdj)
[2021-10-29 15:05:12Z INFO ProcessInvokerWrapper] Process started with process id 396, waiting for process exit.
[2021-10-29 15:05:12Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2021-10-29 15:05:13Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2021-10-29 15:05:13Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2021-10-29 15:05:13Z INFO JobServerQueue] Try to append 1 batches web console lines for record '981b51a9-b3d4-4b18-984c-6b992704d5ee', success rate: 1/1.
[2021-10-29 15:05:13Z INFO JobServerQueue] Try to append 1 batches web console lines for record '29b888a0-a144-5691-0c07-7497e1d5a653', success rate: 1/1.
[2021-10-29 15:05:13Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2021-10-29 15:05:13Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2021-10-29 15:05:13Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2021-10-29 15:05:14Z INFO JobServerQueue] Try to upload 1 log files or attachments, success rate: 1/1.
[2021-10-29 15:05:14Z INFO JobServerQueue] Try to append 1 batches web console lines for record '29b888a0-a144-5691-0c07-7497e1d5a653', success rate: 1/1.
[2021-10-29 15:05:14Z INFO JobServerQueue] Try to append 1 batches web console lines for record '29b888a0-a144-5691-0c07-7497e1d5a653', success rate: 1/1.
[2021-10-29 15:05:18Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2021-10-29 15:05:18Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2021-10-29 15:05:18Z INFO ProcessInvokerWrapper] Exited process 396 with exit code 0
[2021-10-29 15:05:18Z INFO ProcessInvokerWrapper] Finished process 396 with exit code 0, and elapsed time 00:00:05.5358094.
[2021-10-29 15:05:18Z INFO StepsRunner] Step result: Succeeded
[2021-10-29 15:05:18Z INFO StepsRunner] No need for updating job result with current step result 'Succeeded'.
[2021-10-29 15:05:18Z INFO StepsRunner] Current state: job state = ''
[2021-10-29 15:05:18Z INFO StepsRunner] Processing step: DisplayName='Deploy MapProxy', ContinueOnError=False, Enabled=True
[2021-10-29 15:05:18Z INFO ExpressionManager] Evaluating: SucceededNode()
[2021-10-29 15:05:18Z INFO ExpressionManager] Result: True
[2021-10-29 15:05:18Z INFO StepsRunner] Starting the step.
[2021-10-29 15:05:18Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:18Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:18Z INFO HostContext] Well known directory 'Work': '/azp/_work'
[2021-10-29 15:05:18Z INFO HostContext] Well known directory 'Tasks': '/azp/_work/_tasks'
[2021-10-29 15:05:18Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:18Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:18Z INFO HostContext] Well known directory 'Work': '/azp/_work'
[2021-10-29 15:05:18Z INFO HostContext] Well known directory 'TaskZips': '/azp/_work/_taskzips'
[2021-10-29 15:05:18Z INFO TaskManager] Loading task definition '/azp/_work/_tasks/Kubernetes_cbc316a2-586f-4def-be79-488a1f503564/1.181.0/task.json'.
[2021-10-29 15:05:18Z INFO TaskRunner] Get handler data for target platform Linux
[2021-10-29 15:05:18Z INFO TaskRunner] Handler data is of type Microsoft.VisualStudio.Services.Agent.Worker.Node10HandlerData
[2021-10-29 15:05:18Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Worker.IJobExtension'
[2021-10-29 15:05:18Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Worker.Build.ISourceProvider'
[2021-10-29 15:05:18Z INFO BuildJobExtension] The Default Path Root of Build JobExtension is repository.path: /azp/_work/1/s
[2021-10-29 15:05:18Z INFO BuildJobExtension] After prefix Default Path Root provide by JobExtension: /azp/_work/1/s
[2021-10-29 15:05:18Z INFO BuildJobExtension] Return absolute path after prefix DefaultPathRoot: /azp/_work/1/s
[2021-10-29 15:05:18Z INFO TaskRunner] Build JobExtension resolved a rooted path:: /azp/_work/1/s
[2021-10-29 15:05:18Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Worker.IJobExtension'
[2021-10-29 15:05:18Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Worker.Build.ISourceProvider'
[2021-10-29 15:05:18Z INFO BuildJobExtension] The Default Path Root of Build JobExtension is repository.path: /azp/_work/1/s
[2021-10-29 15:05:18Z INFO BuildJobExtension] After prefix Default Path Root provide by JobExtension: /azp/_work/1/s
[2021-10-29 15:05:18Z INFO BuildJobExtension] Return absolute path after prefix DefaultPathRoot: /azp/_work/1/s
[2021-10-29 15:05:18Z INFO TaskRunner] Build JobExtension resolved a rooted path:: /azp/_work/1/s
[2021-10-29 15:05:18Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Worker.IJobExtension'
[2021-10-29 15:05:18Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Worker.Build.ISourceProvider'
[2021-10-29 15:05:18Z INFO BuildJobExtension] The Default Path Root of Build JobExtension is repository.path: /azp/_work/1/s
[2021-10-29 15:05:18Z INFO BuildJobExtension] After prefix Default Path Root provide by JobExtension: /azp/_work/1/s
[2021-10-29 15:05:18Z INFO BuildJobExtension] Return absolute path after prefix DefaultPathRoot: /azp/_work/1/s
[2021-10-29 15:05:18Z INFO TaskRunner] Build JobExtension resolved a rooted path:: /azp/_work/1/s
[2021-10-29 15:05:18Z INFO TaskRunner] The original input is a rooted path, return absolute path: /azp/_work/1/s
[2021-10-29 15:05:18Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:18Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:18Z INFO HostContext] Well known directory 'Work': '/azp/_work'
[2021-10-29 15:05:18Z INFO NodeHandler] Inspect node_modules folder, make sure vsts-task-lib doesn't overwrite String.startsWith/endsWith.
[2021-10-29 15:05:18Z INFO NodeHandler] Scan node_modules folder, looking for vsts-task-lib\extensions.js
[2021-10-29 15:05:18Z INFO NodeHandler] Finished scan and correct extensions.js under vsts-task-lib
[2021-10-29 15:05:18Z INFO NodeHandler] Task.json has node10 handler data: True, use node10 for node tasks: False
[2021-10-29 15:05:18Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:18Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:18Z INFO HostContext] Well known directory 'Externals': '/azp/externals'
[2021-10-29 15:05:18Z INFO ProcessInvokerWrapper] Starting process:
[2021-10-29 15:05:18Z INFO ProcessInvokerWrapper]   File name: '/azp/externals/node10/bin/node'
[2021-10-29 15:05:18Z INFO ProcessInvokerWrapper]   Arguments: '"/azp/_work/_tasks/Kubernetes_cbc316a2-586f-4def-be79-488a1f503564/1.181.0/src//kubernetes.js"'
[2021-10-29 15:05:18Z INFO ProcessInvokerWrapper]   Working directory: '/azp/_work/1/s'
[2021-10-29 15:05:18Z INFO ProcessInvokerWrapper]   Require exit code zero: 'True'
[2021-10-29 15:05:18Z INFO ProcessInvokerWrapper]   Encoding web name:  ; code page: ''
[2021-10-29 15:05:18Z INFO ProcessInvokerWrapper]   Force kill process on cancellation: 'False'
[2021-10-29 15:05:18Z INFO ProcessInvokerWrapper]   Redirected STDIN: 'False'
[2021-10-29 15:05:18Z INFO ProcessInvokerWrapper]   Persist current code page: 'False'
[2021-10-29 15:05:18Z INFO ProcessInvokerWrapper]   Keep redirected STDIN open: 'False'
[2021-10-29 15:05:18Z INFO ProcessInvokerWrapper]   High priority process: 'False'
[2021-10-29 15:05:18Z INFO ProcessInvokerWrapper] Failed to update oom_score_adj for PID: 414.
[2021-10-29 15:05:18Z INFO ProcessInvokerWrapper] System.UnauthorizedAccessException: Access to the path '/proc/414/oom_score_adj' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.FlushWriteBuffer()
   at System.IO.FileStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.StreamWriter.CloseStreamFromDispose(Boolean disposing)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at System.IO.File.WriteAllText(String path, String contents)
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.WriteProcessOomScoreAdj(Int32 processId, Int32 oomScoreAdj)
[2021-10-29 15:05:18Z INFO ProcessInvokerWrapper] Process started with process id 414, waiting for process exit.
[2021-10-29 15:05:18Z INFO JobServerQueue] Try to append 1 batches web console lines for record '29b888a0-a144-5691-0c07-7497e1d5a653', success rate: 1/1.
[2021-10-29 15:05:18Z INFO JobServerQueue] Try to append 1 batches web console lines for record '41e14dad-eb8a-5f61-7fca-186da6f273f6', success rate: 1/1.
[2021-10-29 15:05:19Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2021-10-29 15:05:19Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2021-10-29 15:05:19Z INFO ProcessInvokerWrapper] Exited process 414 with exit code 0
[2021-10-29 15:05:19Z INFO ProcessInvokerWrapper] Finished process 414 with exit code 0, and elapsed time 00:00:00.8138628.
[2021-10-29 15:05:19Z INFO StepsRunner] Step result: Succeeded
[2021-10-29 15:05:19Z INFO StepsRunner] No need for updating job result with current step result 'Succeeded'.
[2021-10-29 15:05:19Z INFO StepsRunner] Current state: job state = ''
[2021-10-29 15:05:19Z INFO JobRunner] Finalize job.
[2021-10-29 15:05:19Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:19Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:19Z INFO HostContext] Well known directory 'Diag': '/azp/_diag'
[2021-10-29 15:05:19Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:19Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:19Z INFO HostContext] Well known directory 'Work': '/azp/_work'
[2021-10-29 15:05:19Z INFO BuildJobExtension] Total accessible running process: 6.
[2021-10-29 15:05:19Z INFO JobRunner] Job result after all job steps finish: Succeeded
[2021-10-29 15:05:19Z INFO JobRunner] Support log upload starting.
[2021-10-29 15:05:19Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:19Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:19Z INFO HostContext] Well known directory 'Work': '/azp/_work'
[2021-10-29 15:05:19Z INFO HostContext] Well known directory 'Temp': '/azp/_work/_temp'
[2021-10-29 15:05:19Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Capabilities.ICapabilitiesProvider'
[2021-10-29 15:05:19Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Capabilities.AgentCapabilitiesProvider, Microsoft.VisualStudio.Services.Agent
[2021-10-29 15:05:19Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Capabilities.EnvironmentCapabilitiesProvider, Microsoft.VisualStudio.Services.Agent
[2021-10-29 15:05:19Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Capabilities.NixCapabilitiesProvider, Microsoft.VisualStudio.Services.Agent
[2021-10-29 15:05:19Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Capabilities.UserCapabilitiesProvider, Microsoft.VisualStudio.Services.Agent
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Ignore: 'AZP_TOKEN'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Ignore: 'AZP_TOKEN_FILE'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Adding '_': '/azp/bin/Agent.Listener'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Adding 'AGENT_ALLOW_RUNASROOT': '1'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Adding 'AZP_ENVIRONMENT': 'NaFRA2 - Review Website'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Adding 'AZP_PROJECT': 'NaFRA2'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Adding 'AZP_URL': 'https://dev.azure.com/jbaconsulting/'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Adding 'DEBIAN_FRONTEND': 'noninteractive'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Adding 'HOME': '/root'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Adding 'HOSTNAME': 'azure-pipelines-environment-agent-677c6c5d89-bc4mn'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Adding 'KUBERNETES_PORT': 'tcp://172.20.0.1:443'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Adding 'KUBERNETES_PORT_443_TCP': 'tcp://172.20.0.1:443'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Adding 'KUBERNETES_PORT_443_TCP_ADDR': '172.20.0.1'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Adding 'KUBERNETES_PORT_443_TCP_PORT': '443'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Adding 'KUBERNETES_PORT_443_TCP_PROTO': 'tcp'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Adding 'KUBERNETES_SERVICE_HOST': '172.20.0.1'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Adding 'KUBERNETES_SERVICE_PORT': '443'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Adding 'KUBERNETES_SERVICE_PORT_HTTPS': '443'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPPROXY_PORT': 'tcp://172.20.204.73:80'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPPROXY_PORT_80_TCP': 'tcp://172.20.204.73:80'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPPROXY_PORT_80_TCP_ADDR': '172.20.204.73'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPPROXY_PORT_80_TCP_PORT': '80'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPPROXY_PORT_80_TCP_PROTO': 'tcp'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPPROXY_SERVICE_HOST': '172.20.204.73'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPPROXY_SERVICE_PORT': '80'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPSERVER_PORT': 'tcp://172.20.143.39:80'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPSERVER_PORT_80_TCP': 'tcp://172.20.143.39:80'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPSERVER_PORT_80_TCP_ADDR': '172.20.143.39'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPSERVER_PORT_80_TCP_PORT': '80'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPSERVER_PORT_80_TCP_PROTO': 'tcp'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPSERVER_SERVICE_HOST': '172.20.143.39'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Adding 'MAPSERVER_SERVICE_PORT': '80'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Adding 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Adding 'PWD': '/azp'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Adding 'REVIEW_WEBSITE_PORT': 'tcp://172.20.218.41:80'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Adding 'REVIEW_WEBSITE_PORT_80_TCP': 'tcp://172.20.218.41:80'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Adding 'REVIEW_WEBSITE_PORT_80_TCP_ADDR': '172.20.218.41'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Adding 'REVIEW_WEBSITE_PORT_80_TCP_PORT': '80'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Adding 'REVIEW_WEBSITE_PORT_80_TCP_PROTO': 'tcp'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Adding 'REVIEW_WEBSITE_SERVICE_HOST': '172.20.218.41'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Adding 'REVIEW_WEBSITE_SERVICE_PORT': '80'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Skipping: 'SHLVL'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Adding 'TF_BUILD': 'True'
[2021-10-29 15:05:19Z INFO EnvironmentCapabilitiesProvider] Adding 'VSO_AGENT_IGNORE': 'AZP_TOKEN,AZP_TOKEN_FILE'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Which: 'android'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Checking file: 'tools/android'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Checking file: '/root/Library/Developer/Xamarin/android-sdk-macosx/tools/android'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Which: 'ant'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Which: 'waagent'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Which: 'bundle'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Which: 'clang'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Which: 'cmake'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Which: 'curl'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Location: '{matches.First()}'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Adding 'curl': '/usr/bin/curl'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Which: 'docker'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Which: 'dotnet'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Which: 'git'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Location: '{matches.First()}'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Adding 'git': '/usr/bin/git'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Which: 'gulp'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Which: 'java'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Which: 'javac'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Which: 'make'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Which: 'mvn'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Which: 'xbuild'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Checking file: '/Library/Frameworks/Mono.framework/Commands/xbuild'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Which: 'msbuild'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Checking file: '/Library/Frameworks/Mono.framework/Commands/msbuild'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Which: 'node'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Which: 'nodejs'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Which: 'npm'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Which: 'python'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Which: 'python3'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Location: '{matches.First()}'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Adding 'python3': '/usr/bin/python3'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Which: 'sh'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Location: '{matches.First()}'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Adding 'sh': '/bin/sh'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Which: 'svn'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Which: 'ruby'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Which: 'rake'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Which: 'svn'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Which: 'mdtool'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Checking file: '/Applications/Xamarin Studio.app/Contents/MacOS/mdtool'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Checking file: '/Applications/Visual Studio.app/Contents/MacOS/vstool'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Which: 'generator'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Checking file: '/Library/Frameworks/Xamarin.Android.framework/Commands/generator'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Checking file: '/Library/Frameworks/Xamarin.Android.framework/Versions/Current/Version'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Which: 'xcode-select'
[2021-10-29 15:05:19Z INFO CapabilitiesBuilder] Not found.
[2021-10-29 15:05:19Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:19Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:19Z INFO AgentCapabilitiesProvider] Adding 'Agent.Name': 'azure-pipelines-environment-agent-677c6c5d89-bc4mn'
[2021-10-29 15:05:19Z INFO AgentCapabilitiesProvider] Adding 'Agent.OS': 'Linux'
[2021-10-29 15:05:19Z INFO AgentCapabilitiesProvider] Adding 'Agent.OSArchitecture': 'X64'
[2021-10-29 15:05:19Z INFO AgentCapabilitiesProvider] Adding 'InteractiveSession': 'True'
[2021-10-29 15:05:19Z INFO AgentCapabilitiesProvider] Adding 'Agent.Version': '2.194.0'
[2021-10-29 15:05:19Z INFO AgentCapabilitiesProvider] Adding 'Agent.ComputerName': 'azure-pipelines-environment-agent-677c6c5d89-bc4mn'
[2021-10-29 15:05:19Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:19Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:19Z INFO AgentCapabilitiesProvider] Adding 'Agent.HomeDirectory': '/azp'
[2021-10-29 15:05:19Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:19Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:19Z INFO HostContext] Well known directory 'Diag': '/azp/_diag'
[2021-10-29 15:05:19Z INFO HostContext] Well known directory 'Bin': '/azp/bin.2.194.0'
[2021-10-29 15:05:19Z INFO HostContext] Well known directory 'Root': '/azp'
[2021-10-29 15:05:19Z INFO HostContext] Well known directory 'Diag': '/azp/_diag'
[2021-10-29 15:05:19Z INFO JobRunner] Support log upload complete.
[2021-10-29 15:05:19Z INFO JobRunner] Completing the job execution context.
[2021-10-29 15:05:19Z INFO JobRunner] Shutting down the job server queue.
[2021-10-29 15:05:19Z INFO JobServerQueue] Fire signal to shutdown all queues.
[2021-10-29 15:05:19Z INFO JobServerQueue] Try to append 2 batches web console lines for record '41e14dad-eb8a-5f61-7fca-186da6f273f6', success rate: 2/2.
[2021-10-29 15:05:19Z INFO JobServerQueue] All queue process task stopped.
[2021-10-29 15:05:19Z INFO JobServerQueue] Skip 3 batches web console lines for last run
[2021-10-29 15:05:19Z INFO JobServerQueue] Try to append 2 batches web console lines for record '41e14dad-eb8a-5f61-7fca-186da6f273f6', success rate: 2/2.
[2021-10-29 15:05:19Z INFO JobServerQueue] Try to append 1 batches web console lines for record '45f00212-1083-4248-837a-f39f6cebec4f', success rate: 1/1.
[2021-10-29 15:05:20Z INFO JobServerQueue] Try to append 1 batches web console lines for record 'a2a17486-12d8-5347-a845-7ac6ecb43493', success rate: 1/1.
[2021-10-29 15:05:20Z INFO JobServerQueue] Web console line queue drained.
[2021-10-29 15:05:20Z INFO JobServerQueue] Uploading 6 files in one shot.
[2021-10-29 15:05:21Z INFO JobServerQueue] Try to upload 6 log files or attachments, success rate: 6/6.
[2021-10-29 15:05:21Z INFO JobServerQueue] File upload queue drained.
[2021-10-29 15:05:21Z INFO JobServerQueue] Timeline update queue drained.
[2021-10-29 15:05:21Z INFO JobServerQueue] All queue process tasks have been stopped, and all queues are drained.
[2021-10-29 15:05:21Z INFO TempDirectoryManager] Cleaning agent temp folder: /azp/_work/_temp
[2021-10-29 15:05:21Z INFO JobRunner] Raising job completed event.
[2021-10-29 15:05:21Z INFO Worker] Job completed.
```
</details>

### PR DESCRIPTION
**Pull request by AndreyIvanov42**
Updating the agent running in a docker container causes its crash. The process that manages the agent in a container doesn't correctly handle exit codes and doesn't pass the required arguments to the agent. 

This PR has fixed this behavior.

Tested on Ubuntu:18.04 image with and without `--once` flag

With once
Agent wait -> Update agent -> Agent wait
Agent wait -> Update agent -> Agent wait -> Run Job -> Exit
Without once
Agent wait -> Update agent -> Agent wait
Agent wait -> Update agent -> Agent wait -> Run Job -> Agent wait
Run Job -> Update agent -> Agent wait

Related issue - https://github.com/microsoft/azure-pipelines-agent/issues/3587

### CODE REVIEW

File: src/Misc/layoutroot/run.sh [hunk 1]
```diff
@@ -37,32 +37,55 @@ DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
...
 
-        if [ ! -x "$DIR"/bin/Agent.Listener ]; then
-            echo "Failed to update within 20 seconds." >&2
-            exit 1
-        fi
-        
-        "$DIR"/bin/Agent.Listener run $*
+function runAgent {
+    if [[ "$FIRST_ARG" == "localRun" ]]; then
+        "$DIR"/bin/Agent.Listener
```
Comment (anatolybolshakov) [inline src/Misc/layoutroot/run.sh:54]: Should the $ARGUMENTS be passed here as well?

File: src/Misc/layoutroot/run.sh [hunk 2]
```diff
@@ -37,32 +37,55 @@ DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
...
+        fi
+
+        # Return code 3 or 4 means the agent received an update message.
+        # Sleep at least 5 seconds (to allow the update process to start) and
+        # at most 20 seconds (to allow it to finish) then run the new agent
+        # again.
+        returnCode=$?
+        echo "Agent exit code $returnCode"
+
+        if [[ $returnCode == 3 || $returnCode == 4 ]]; then
```
Comment (anatolybolshakov) [inline src/Misc/layoutroot/run.sh:70]: What happens if there will be some other return code?

File: src/Misc/layoutroot/run.sh (hunk 1 above)
Comment (AndreyIvanov42) [reply src/Misc/layoutroot/run.sh]: Fixed, Thanks

File: src/Misc/layoutroot/run-docker.sh [hunk 3]
```diff
@@ -0,0 +1,91 @@
...
+ARGUMENTS=$*
+
+function runAgent {
+    if [[ "$FIRST_ARG" == "localRun" ]]; then
+        "$DIR"/bin/Agent.Listener $ARGUMENTS
+    else
+        if [[ "$ONCE" = true ]]; then
+            "$DIR"/bin/Agent.Listener run $ARGUMENTS
+        else
+            echo "Starting Agent listener with startup type: service"
```
Comment (anatolybolshakov) [inline src/Misc/layoutroot/run-docker.sh:59]: I think this could lead to some confusion - since this is not a service run mode (comparing to interactive), but rather the parameter which basically just disables agent run as a separate process after self-update (which although is used in a service agent mode). Could it be better here like below?
"Starting Agent listener with startup type: service - to prevent running of an agent in a separate process after self-update."

File: src/Misc/layoutroot/run-docker.sh [hunk 4]
```diff
@@ -0,0 +1,91 @@
...
+for a in $*; do
+    if [[ "$a" == "--once" ]]; then
+        ONCE=true
+    fi
+done
+
+FIRST_ARG=$1
+ARGUMENTS=$*
+
+function runAgent {
```
Comment (anatolybolshakov) [inline src/Misc/layoutroot/run-docker.sh:52]: Could you please add comments to all new functions?

**Review by anatolybolshakov — APPROVED** [review]
LGTM in general, thanks! Please also take a look at comments.
Let's also make sure that we've completed buddy testing as well.

File: src/Misc/layoutroot/run-docker.sh (hunk 4 above)
Comment (AndreyIvanov42) [reply src/Misc/layoutroot/run-docker.sh:52]: Sure

File: src/Misc/layoutroot/run-docker.sh (hunk 3 above)
Comment (AndreyIvanov42) [reply src/Misc/layoutroot/run-docker.sh:59]: I agree, it will be better

**Review by max-zaytsev — APPROVED** [review]
